# Institutional-Grade Complex Strategy
name: "adaptive_multi_timeframe"
description: "6-indicator confluence with multi-timeframe analysis"
version: "1.0"

# Data requirements
data:
  symbols: ["SPX", "NDX", "EURUSD", "USDJPY"]
  timeframes: ["15m", "1h", "4h", "1d"]  # Multiple timeframes
  history_required: 500  # Extended for daily analysis

# Technical indicators configuration
indicators:
  # Trend indicators
  - name: macd
    fast_period: 12
    slow_period: 26
    signal_period: 9
  - name: adx
    period: 14
  - name: ema
    periods: [20, 50, 200]
    
  # Momentum indicators
  - name: rsi
    period: 14
  - name: stochastic
    k_period: 14
    d_period: 3
    smooth: 3
    
  # Volatility indicators
  - name: bollinger_bands
    period: 20
    std_dev: 2.0
  - name: atr
    period: 14
    
  # Volume indicators
  - name: vwap
    period: 1
  - name: obv
    period: 20
  - name: mfi
    period: 14

# Complex fuzzy logic configuration
fuzzy_sets:
  trend_strength:
    strong_bear:
      type: gaussian
      parameters: [-1.0, 0.2]
    weak_bear:
      type: gaussian
      parameters: [-0.5, 0.15]
    neutral:
      type: gaussian
      parameters: [0, 0.1]
    weak_bull:
      type: gaussian
      parameters: [0.5, 0.15]
    strong_bull:
      type: gaussian
      parameters: [1.0, 0.2]
  
  momentum_quality:
    oversold:
      type: trapezoidal
      parameters: [0, 0, 20, 30]
    neutral:
      type: triangular
      parameters: [25, 50, 75]
    overbought:
      type: trapezoidal
      parameters: [70, 80, 100, 100]
  
  volatility_regime:
    low:
      type: gaussian
      parameters: [0.5, 0.1]
    normal:
      type: gaussian
      parameters: [1.0, 0.15]
    high:
      type: gaussian
      parameters: [2.0, 0.3]
    extreme:
      type: gaussian
      parameters: [3.0, 0.5]
  
  confluence_score:
    weak:
      type: triangular
      parameters: [0, 0.2, 0.4]
    moderate:
      type: triangular
      parameters: [0.3, 0.5, 0.7]
    strong:
      type: triangular
      parameters: [0.6, 0.8, 1.0]

# Advanced neural network configuration
model:
  type: "transformer"  # Self-attention for complex patterns
  architecture:
    n_heads: 8
    n_layers: 4
    d_model: 128
    d_ff: 512
    max_seq_length: 50
    dropout: 0.2
    
  training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 300
    optimizer: "adam"
    weight_decay: 0.0001
    gradient_clip: 1.0
    
    lr_scheduler:
      type: "one_cycle"
      max_lr: 0.003
      pct_start: 0.3
    
    early_stopping:
      patience: 40
      monitor: "val_sharpe_ratio"  # Custom metric
      mode: "max"
  
  features:
    include_price_context: true
    include_volume_context: true
    include_intermarket: true     # Correlations
    include_seasonality: true     # Time-based features
    lookback_periods: 20          # Extended context
    scale_features: true
    scaling_method: "robust"

# Sophisticated decision logic
decisions:
  output_format: "regression"     # Continuous confidence scores
  confidence_threshold: 0.70      # High threshold
  position_awareness: true
  
  # Multi-timeframe alignment
  timeframe_weights:
    "15m": 0.1
    "1h": 0.3
    "4h": 0.4
    "1d": 0.2
  
  filters:
    min_signal_separation: 8
    volume_filter: true
    correlation_filter: true      # Avoid correlated trades
    regime_filter: true          # Adapt to market regime

# Institutional-level orchestration
orchestrator:
  max_position_size: 0.90
  signal_cooldown: 10
  
  # Confluence requirements
  min_indicators_aligned: 4       # At least 4 of 6
  
  # Regime detection
  regime_detection:
    method: "hidden_markov"
    states: ["trending", "ranging", "volatile"]
    
  # Adaptive parameters
  adaptive_rules:
    trending:
      use_momentum: true
      trend_filter_strength: 0.8
    ranging:
      use_mean_reversion: true
      band_trading: true
    volatile:
      reduce_position_size: 0.5
      widen_stops: 1.5
  
  entry_rules:
    long:
      - confluence_score_strong: "> 0.7"
      - trend_strength_bull: "> 0.6"
      - momentum_quality_not_overbought: true
      - volatility_regime_not_extreme: true
      - timeframe_alignment: "> 0.7"
    
  modes:
    backtest:
      confidence_threshold: 0.65
    paper:
      confidence_threshold: 0.70
    live:
      confidence_threshold: 0.75
      require_human_confirmation: true

# Sophisticated training
training:
  method: "reinforcement_learning"  # Advanced approach
  
  # Hybrid training
  initial_supervised:
    labels:
      source: "zigzag"
      zigzag_threshold: 0.03
      label_lookahead: 40
    epochs: 100
  
  # Then RL fine-tuning
  rl_config:
    algorithm: "PPO"
    episodes: 1000
    reward_function: "sharpe_ratio"
    
  data_split:
    train: 0.6
    validation: 0.2
    test: 0.2
    
  # Walk-forward analysis
  walk_forward:
    window_size: 252  # 1 year
    step_size: 21    # Monthly
    
  fitness_metrics:
    primary: "sharpe_ratio"
    secondary: ["calmar_ratio", "sortino_ratio", "max_drawdown"]

# Professional risk management
risk_management:
  position_sizing: "risk_parity"
  target_volatility: 0.12        # 12% annual vol target
  
  # Dynamic risk budgeting
  risk_budget:
    base_risk: 0.01             # 1% base
    max_risk: 0.03              # 3% maximum
    volatility_scalar: true
    correlation_adjustment: true
    
  max_portfolio_risk: 0.10
  
  # Sophisticated stops
  stop_loss:
    type: "chandelier"
    atr_period: 22
    multiplier: 3.0
    
  # Volatility-based targets
  take_profit:
    type: "volatility_targets"
    target_1: "1.5_sigma"
    target_2: "2.5_sigma"
    target_3: "4.0_sigma"

# Professional backtesting
backtesting:
  start_date: "2015-01-01"      # Extended history
  end_date: "2024-01-01"
  initial_capital: 1000000      # Institutional size
  
  # Realistic costs
  transaction_costs:
    stocks: 0.0005
    forex: 0.00002              # 2 pips
    futures: 0.00015
    
  slippage_model: "square_root"  # Impact = k * sqrt(size)
  
  # Monte Carlo analysis
  monte_carlo:
    simulations: 1000
    confidence_intervals: [0.05, 0.25, 0.75, 0.95]
