# Volatility Breakout Strategy
name: "bollinger_squeeze_volume"
description: "Captures volatility expansion after BB squeeze with volume confirmation"
version: "1.0"

# Data requirements
data:
  symbols: ["EURUSD", "GBPUSD", "BTCUSD", "ETHUSD"]
  timeframes: ["1h", "4h", "1d"]
  history_required: 150  # For 6-month volatility comparison

# Technical indicators configuration
indicators:
  - name: bollinger_bands
    period: 20
    std_dev: 2.0
    source: close
  - name: keltner_channels
    period: 20
    atr_period: 10
    multiplier: 1.5
  - name: volume_sma
    period: 20
  - name: atr
    period: 14
  - name: momentum
    period: 12
  # Derived indicators (now available as proper indicator classes)
  - name: bollinger_band_width
    bollinger_bands_source: "bollinger_bands"
  - name: volume_ratio
    volume_sma_source: "volume_sma"
  - name: squeeze_intensity
    bollinger_bands_source: "bollinger_bands"
    keltner_channels_source: "keltner_channels"

# Fuzzy logic configuration
fuzzy_sets:
  bollinger_band_width:
    very_tight:
      type: triangular
      parameters: [0, 0.002, 0.005]
    tight:
      type: triangular
      parameters: [0.003, 0.008, 0.015]
    normal:
      type: triangular
      parameters: [0.010, 0.020, 0.030]
    wide:
      type: triangular
      parameters: [0.025, 0.040, 0.060]
    very_wide:
      type: triangular
      parameters: [0.050, 0.080, 0.120]
  
  volume_ratio:
    low:
      type: triangular
      parameters: [0, 0.5, 1.0]
    normal:
      type: triangular
      parameters: [0.8, 1.0, 1.2]
    high:
      type: triangular
      parameters: [1.0, 1.5, 2.0]
    very_high:
      type: triangular
      parameters: [1.5, 2.5, 4.0]
  
  squeeze_intensity:
    no_squeeze:
      type: triangular
      parameters: [0, 0.2, 0.4]
    light_squeeze:
      type: triangular
      parameters: [0.3, 0.5, 0.7]
    strong_squeeze:
      type: triangular
      parameters: [0.6, 0.8, 1.0]

# Neural network configuration
model:
  type: "mlp"
  architecture:
    hidden_layers: [40, 20, 10]  # More complex for pattern recognition
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.25
  
  training:
    learning_rate: 0.0008
    batch_size: 32
    epochs: 200
    optimizer: "adam"
    weight_decay: 0.0001
    
    lr_scheduler:
      type: "cosine_annealing"
      T_max: 50
    
    early_stopping:
      patience: 30
      monitor: "val_loss"
      min_delta: 0.0001
  
  features:
    include_price_context: true
    include_volume_context: true
    include_volatility_history: true
    lookback_periods: 5          # Squeeze development pattern
    scale_features: true
    scaling_method: "minmax"

# Decision logic configuration
decisions:
  output_format: "classification"
  confidence_threshold: 0.65     # Moderate threshold
  position_awareness: true
  
  filters:
    min_signal_separation: 5     # Avoid multiple entries in same squeeze
    volume_filter: true
    min_volume_ratio: 1.5       # 150% of average

# Strategy specific rules
orchestrator:
  max_position_size: 0.85
  signal_cooldown: 6
  
  # Squeeze detection
  squeeze_detection:
    method: "bb_inside_kc"      # BB inside Keltner Channels
    min_squeeze_bars: 3         # Minimum squeeze duration
    
  entry_rules:
    long:
      - squeeze_intensity_strong: "> 0.6"
      - price_breaks_upper_band: true
      - volume_ratio_very_high: "> 0.7"
      - momentum_positive: true
    short:
      - squeeze_intensity_strong: "> 0.6"
      - price_breaks_lower_band: true
      - volume_ratio_very_high: "> 0.7"
      - momentum_negative: true
  
  modes:
    backtest:
      confidence_threshold: 0.60
    paper:
      confidence_threshold: 0.65
    live:
      confidence_threshold: 0.70

# Training configuration
training:
  method: "supervised"
  labels:
    source: "zigzag"
    zigzag_threshold: 0.04      # 4% for breakout moves
    label_lookahead: 30         # Longer for momentum continuation
  
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  
  fitness_metrics:
    primary: "risk_reward_ratio"
    secondary: ["win_rate", "profit_factor"]

# Risk management
risk_management:
  position_sizing: "volatility_based"
  base_risk: 0.02              # 2% base risk
  volatility_scalar: true       # Adjust by ATR
  max_portfolio_risk: 0.08     # 8% total
  
  stop_loss:
    type: "bb_based"
    placement: "opposite_band"  # Stop at opposite BB
    atr_buffer: 0.5            # Add 0.5 ATR buffer
  
  take_profit:
    type: "atr_based"
    atr_multiplier: 3.0        # 1:3 risk-reward target

# Backtesting configuration
backtesting:
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  initial_capital: 100000
  transaction_costs: 0.001
  slippage: 0.0008             # Higher for breakouts
