# High Win-Rate Aggressive Scalping Strategy
name: "crypto_ema_scalping"
description: "Multi-EMA alignment for rapid crypto scalping"
version: "1.0"

# Data requirements
data:
  symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT"]
  timeframes: ["1m", "5m", "15m"]  # Ultra-short timeframes
  history_required: 100

# Technical indicators configuration
indicators:
  - name: ema
    periods: [8, 13, 21]  # Scalping EMAs
  - name: rsi
    period: 5            # Ultra-fast RSI
  - name: volume_profile
    period: 100
    bins: 20
  - name: atr
    period: 10
  - name: vwap
    period: 1            # Session VWAP
  - name: order_flow_imbalance
    period: 20           # Custom microstructure

# Fuzzy logic for rapid decisions
fuzzy_sets:
  ema_alignment:
    perfect_bull:
      type: triangular
      parameters: [0.8, 0.9, 1.0]
    good_bull:
      type: triangular
      parameters: [0.6, 0.7, 0.8]
    neutral:
      type: triangular
      parameters: [0.4, 0.5, 0.6]
    good_bear:
      type: triangular
      parameters: [0.2, 0.3, 0.4]
    perfect_bear:
      type: triangular
      parameters: [0, 0.1, 0.2]
  
  momentum_speed:
    slow:
      type: triangular
      parameters: [0, 25, 50]
    moderate:
      type: triangular
      parameters: [40, 60, 80]
    fast:
      type: triangular
      parameters: [70, 85, 100]
  
  volume_intensity:
    low:
      type: gaussian
      parameters: [0.5, 0.2]
    normal:
      type: gaussian
      parameters: [1.0, 0.3]
    high:
      type: gaussian
      parameters: [2.0, 0.5]

# Lightweight neural network for speed
model:
  type: "mlp"  # Simple for fast inference
  architecture:
    hidden_layers: [15, 8]  # Minimal layers
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.1          # Light dropout
  
  training:
    learning_rate: 0.003  # Faster learning
    batch_size: 128       # Large batches
    epochs: 100
    optimizer: "adam"
    
    # No complex scheduling for speed
    early_stopping:
      patience: 15
      monitor: "val_loss"
  
  features:
    include_price_context: true
    include_volume_context: true
    include_order_book: true    # Level 2 data
    lookback_periods: 3         # Recent only
    scale_features: true
    scaling_method: "minmax"

# Rapid decision making
decisions:
  output_format: "classification"
  confidence_threshold: 0.60    # Moderate for frequency
  position_awareness: true
  
  # Ultra-fast execution
  latency_requirements:
    max_decision_time: 50       # 50ms max
    
  filters:
    min_signal_separation: 1    # Allow rapid trades
    volume_filter: true
    spread_filter: true         # Check bid-ask

# Scalping-specific orchestration
orchestrator:
  max_position_size: 0.50       # Multiple positions
  max_concurrent_positions: 3   # Diversification
  signal_cooldown: 1
  
  # Session-based trading
  trading_sessions:
    active_hours: ["00:00-04:00", "12:00-16:00"]  # UTC high volume
    
  entry_rules:
    long:
      - ema_alignment_perfect_bull: "> 0.8"
      - momentum_speed_fast: "> 0.7"
      - volume_intensity_high: "> 0.6"
      - spread_percentage: "< 0.1"  # Max 0.1% spread
    short:
      - ema_alignment_perfect_bear: "> 0.8"
      - momentum_speed_fast: "> 0.7"
      - volume_intensity_high: "> 0.6"
      - spread_percentage: "< 0.1"
  
  # Quick exits
  exit_rules:
    time_limit: 5              # Max 5 minutes
    profit_target: 0.003       # 0.3% quick profit
    stop_loss: 0.002          # 0.2% tight stop
    
  modes:
    backtest:
      confidence_threshold: 0.55
    paper:
      confidence_threshold: 0.60
      max_trades_per_hour: 20
    live:
      confidence_threshold: 0.65
      max_trades_per_hour: 10  # Risk control

# High-frequency training
training:
  method: "supervised"
  
  # Micro-movement labels
  labels:
    source: "tick_bars"        # Volume-based bars
    tick_size: 1000           # 1000 trades per bar
    label_method: "next_tick"  # Immediate next movement
    
  # Handle massive dataset
  data_sampling:
    method: "stratified"
    sample_size: 1000000      # 1M samples
    
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
    
  fitness_metrics:
    primary: "win_rate"
    secondary: ["trades_per_day", "profit_per_trade"]

# Crypto-specific risk management
risk_management:
  position_sizing: "fixed_dollar"
  position_size: 1000          # $1000 per trade
  
  # Account for crypto volatility
  max_daily_loss: 0.05         # 5% daily stop
  max_trades_per_day: 100      # Frequency limit
  
  # Exchange-specific
  fee_structure:
    maker: 0.0002             # 0.02% maker
    taker: 0.0004             # 0.04% taker
    
  # Micro stops
  stop_loss:
    type: "percentage"
    value: 0.002              # 0.2% stop
    
  take_profit:
    type: "percentage"
    value: 0.003              # 0.3% target
    
  # Anti-liquidation
  leverage_control:
    max_leverage: 3           # Conservative for crypto
    margin_buffer: 0.5        # 50% margin buffer

# High-frequency backtesting
backtesting:
  start_date: "2023-01-01"    # Recent data only
  end_date: "2024-01-01"
  initial_capital: 10000      # Smaller for scalping
  
  # Realistic crypto costs
  transaction_costs: 0.0004    # Taker fees
  slippage: 0.0002            # Minimal on liquid pairs
  
  # Tick-level simulation
  data_frequency: "tick"
  order_book_depth: 10        # Levels to simulate
