backtesting:
  end_date: '2024-01-01'
  initial_capital: 100000
  slippage: 0.0005
  start_date: '2020-01-01'
  transaction_costs: 0.001
decisions:
  confidence_threshold: 0.6
  filters:
    min_signal_separation: 4
    volume_filter: false
  output_format: classification
  position_awareness: true
description: A strategy focused on mean reversion signals with specialized fuzzy sets
fuzzy_sets:
  atr:
    high:
    - 2.5
    - 4
    - 100
    low:
    - 0
    - 0.5
    - 1.5
    medium:
    - 1
    - 2
    - 3
  bbands:
    above:
    - 0.5
    - 1.5
    - 2.5
    below:
    - -2.5
    - -1.5
    - -0.5
    far_above:
    - 2
    - 3
    - 100
    far_below:
    - -100
    - -3
    - -2
    neutral:
    - -1
    - 0
    - 1
  rsi:
    extreme_overbought:
    - 75
    - 90
    - 100
    extreme_oversold:
    - 0
    - 10
    - 25
    neutral:
    - 35
    - 50
    - 65
    overbought:
    - 55
    - 70
    - 85
    oversold:
    - 15
    - 30
    - 45
  volatility:
    high:
    - 50
    - 70
    - 80
    low:
    - 10
    - 20
    - 30
    normal:
    - 25
    - 40
    - 55
    very_high:
    - 75
    - 90
    - 100
    very_low:
    - 0
    - 5
    - 15
indicators:
- name: rsi
  period: 7
  source: close
- name: bbands
  period: 20
  source: close
  std_dev: 2.5
- name: atr
  period: 14
  source: close
- name: volatility
  period: 20
  source: close
model:
  architecture:
    activation: relu
    dropout: 0.2
    hidden_layers:
    - 20
    - 10
    output_activation: softmax
  features:
    include_price_context: true
    include_raw_indicators: false
    include_volume_context: false
    lookback_periods: 3
    scale_features: true
    scaling_method: standard
  hidden_layers:
  - 30
  - 15
  input_size: 15
  output_size: 2
  training:
    batch_size: 32
    early_stopping:
      min_delta: 0.0001
      monitor: val_loss
      patience: 15
    epochs: 100
    learning_rate: 0.001
    optimizer: adam
    weight_decay: 0.0001
  type: mlp
name: neuro_mean_reversion_strategy
orchestrator:
  max_position_size: 0.95
  modes:
    backtest:
      confidence_threshold: 0.6
    live:
      confidence_threshold: 0.7
      require_confirmation: true
    paper:
      confidence_threshold: 0.65
  signal_cooldown: 4
risk_management:
  max_portfolio_risk: 0.1
  position_sizing: fixed_fraction
  risk_per_trade: 0.02
training:
  data_split:
    test: 0.15
    train: 0.7
    validation: 0.15
  fitness_metrics:
    primary: accuracy
    secondary:
    - precision
    - recall
    - f1_score
  labels:
    label_lookahead: 20
    source: zigzag
    zigzag_threshold: 0.05
  method: supervised
version: 1.0.neuro
