name: mean_reversion_confluence_v1
description: Mean reversion strategy with trend and momentum confluence filters
version: '1.0'
hypothesis: Mean reversion opportunities are most profitable when trend strength is
  moderate and momentum confirms the potential reversal
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 150
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: RSI
  feature_id: rsi_14
  period: 14
  source: close
- name: ADX
  feature_id: adx_14
  period: 14
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 25
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate_trend:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong_trend:
      type: triangular
      parameters:
      - 45
      - 70
      - 100
  macd_12:
    bearish:
      type: triangular
      parameters:
      - -1.0
      - -0.2
      - 0
    neutral:
      type: triangular
      parameters:
      - -0.1
      - 0
      - 0.1
    bullish:
      type: triangular
      parameters:
      - 0
      - 0.2
      - 1.0
model:
  type: mlp
  architecture:
    hidden_layers:
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 40
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 8
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
