name: mean_reversion_momentum_v2
description: Mean reversion strategy using momentum divergence and trend exhaustion
  signals
version: '3.0'
hypothesis: Markets overextend and reverse when momentum diverges from price and trend
  strength weakens
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  macd_12_26_9:
    type: MACD
    period: 26
    source: close
  rsi_14:
    type: RSI
    period: 14
    source: close
  adx_14:
    type: ADX
    period: 14
    source: close
  ema_20:
    type: EMA
    period: 20
    source: close
fuzzy_sets:
  macd_12_26_9:
    strong_bearish:
      type: triangular
      parameters:
      - -0.01
      - -0.005
      - -0.002
    weak_bearish:
      type: triangular
      parameters:
      - -0.003
      - -0.001
      - 0
    neutral:
      type: triangular
      parameters:
      - -0.001
      - 0
      - 0.001
    weak_bullish:
      type: triangular
      parameters:
      - 0
      - 0.001
      - 0.003
    strong_bullish:
      type: triangular
      parameters:
      - 0.002
      - 0.005
      - 0.01
    indicator: macd_12_26_9
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 25
      - 35
    neutral_low:
      type: triangular
      parameters:
      - 30
      - 40
      - 50
    neutral:
      type: triangular
      parameters:
      - 40
      - 50
      - 60
    neutral_high:
      type: triangular
      parameters:
      - 50
      - 60
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 75
      - 100
    indicator: rsi_14
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate_trend:
      type: triangular
      parameters:
      - 20
      - 30
      - 40
    strong_trend:
      type: triangular
      parameters:
      - 35
      - 50
      - 70
    very_strong_trend:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
    indicator: adx_14
  ema_20:
    price_below:
      type: triangular
      parameters:
      - -0.02
      - -0.01
      - -0.002
    price_at:
      type: triangular
      parameters:
      - -0.003
      - 0
      - 0.003
    price_above:
      type: triangular
      parameters:
      - 0.002
      - 0.01
      - 0.02
    indicator: ema_20
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 80
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: macd_12_26_9
  timeframes: all
- fuzzy_set: rsi_14
  timeframes: all
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: ema_20
  timeframes: all
