# Mean Reversion Strategy Configuration
name: mean_reversion_strategy
description: A strategy focused on mean reversion signals with specialized fuzzy sets

indicators:
  - name: rsi
    period: 14
    source: close
  - name: sma
    period: 20
    source: close
  - name: ema
    period: 12
    source: close

# Custom fuzzy set definitions that override the defaults in config/fuzzy.yaml
fuzzy_sets:
  # RSI fuzzy sets
  rsi:
    oversold:
      type: triangular
      parameters: [0, 10, 30]
    neutral:
      type: triangular
      parameters: [20, 50, 80]
    overbought:
      type: triangular
      parameters: [70, 90, 100]

  # SMA position fuzzy sets (price relative to SMA)
  sma:
    below:
      type: triangular
      parameters: [0.85, 0.95, 1.0]
    neutral:
      type: triangular
      parameters: [0.98, 1.0, 1.02]
    above:
      type: triangular
      parameters: [1.0, 1.05, 1.15]

  # EMA position fuzzy sets (price relative to EMA)
  ema:
    below:
      type: triangular
      parameters: [0.85, 0.95, 1.0]
    neutral:
      type: triangular
      parameters: [0.98, 1.0, 1.02]
    above:
      type: triangular
      parameters: [1.0, 1.05, 1.15]

# Neural network configuration for this strategy
model:
  type: mlp
  architecture:
    hidden_layers: [64, 32, 16]
    dropout_rate: 0.2
    activation: "relu"
    output_activation: "softmax"
  training:
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
    optimizer: "adam"
    loss_function: "cross_entropy"
    early_stopping_patience: 10
  features:
    include_price_features: true
    include_technical_features: true
    include_fuzzy_features: true
    lookback_window: 10

# Training configuration
training:
  # Label generation configuration
  labels:
    method: "zigzag"
    zigzag_threshold: 0.05  # 5% threshold for significant moves
    label_lookahead: 24     # Look ahead 24 hours for labeling
  
  # Data split configuration
  data_split:
    train: 0.7      # 70% for training
    validation: 0.2 # 20% for validation
    test: 0.1       # 10% for testing