name: momentum_acceleration_v1
description: Multi-timeframe momentum acceleration strategy using ROC, ATR, and Williams
  %R
version: '1.0'
hypothesis: Price momentum that accelerates consistently across timeframes indicates
  stronger directional moves than single-timeframe signals
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
  timeframes:
    mode: multi_timeframe
    list:
    - 1h
    - 4h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: roc
  feature_id: roc_12_1h
  period: 12
  source: close
  timeframe: 1h
- name: roc
  feature_id: roc_12_4h
  period: 12
  source: close
  timeframe: 4h
- name: atr
  feature_id: atr_14
  period: 14
  timeframe: 1h
- name: williamsr
  feature_id: williams_r_14
  period: 14
  timeframe: 1h
fuzzy_sets:
  roc_12_1h:
    strong_negative:
      type: triangular
      parameters:
      - -10
      - -3
      - -1
    weak_negative:
      type: triangular
      parameters:
      - -2
      - -0.5
      - 0
    neutral:
      type: triangular
      parameters:
      - -0.5
      - 0
      - 0.5
    weak_positive:
      type: triangular
      parameters:
      - 0
      - 0.5
      - 2
    strong_positive:
      type: triangular
      parameters:
      - 1
      - 3
      - 10
  roc_12_4h:
    strong_negative:
      type: triangular
      parameters:
      - -15
      - -5
      - -2
    weak_negative:
      type: triangular
      parameters:
      - -3
      - -1
      - 0
    neutral:
      type: triangular
      parameters:
      - -1
      - 0
      - 1
    weak_positive:
      type: triangular
      parameters:
      - 0
      - 1
      - 3
    strong_positive:
      type: triangular
      parameters:
      - 2
      - 5
      - 15
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0
      - 0.001
      - 0.003
    medium_volatility:
      type: triangular
      parameters:
      - 0.002
      - 0.004
      - 0.006
    high_volatility:
      type: triangular
      parameters:
      - 0.005
      - 0.008
      - 0.015
  williams_r_14:
    oversold:
      type: triangular
      parameters:
      - -100
      - -85
      - -65
    neutral:
      type: triangular
      parameters:
      - -70
      - -50
      - -30
    overbought:
      type: triangular
      parameters:
      - -35
      - -15
      - 0
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: true
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
