name: mtf_forex_neural
description: Multi-timeframe forex neural strategy using 30+ indicators across momentum, trend, volatility, and volume. Trained
  on major forex pairs with 5m entry signals, 1h intermediate trend, and 1d major trend context.
version: '2.0'
hypothesis: Forex markets exhibit consistent multi-timeframe patterns across major pairs. By combining momentum oscillators
  for entry timing, trend indicators for directional bias, volatility measures for regime adaptation, and volume proxies for
  institutional flow, the neural network can learn generalizable trading patterns that work across different currency pairs
  and market conditions.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
    - AUDUSD
    - EURJPY
    - EURGBP
    - AUDJPY
  timeframes:
    mode: multi_timeframe
    list:
    - 5m
    - 1h
    - 1d
    base_timeframe: 5m
  history_required: 300
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: multi_timeframe
    supported:
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
indicators:
- indicator: rsi
  name: rsi_14
  period: 14
  source: close
- indicator: rsi
  name: rsi_7
  period: 7
  source: close
- indicator: rsi
  name: rsi_21
  period: 21
  source: close
- indicator: macd
  name: macd_12_26_9
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: close
- indicator: macd
  name: macd_5_13_5
  fast_period: 5
  slow_period: 13
  signal_period: 5
  source: close
- indicator: stoch
  name: stoch_3_14
  k_period: 14
  d_period: 3
  source: close
- indicator: stoch
  name: stoch_3_5
  k_period: 5
  d_period: 3
  source: close
- indicator: cci
  name: cci_20
  period: 20
  source: close
- indicator: momentum
  name: momentum_10
  period: 10
  source: close
- indicator: roc
  name: roc_12
  period: 12
  source: close
- indicator: williamsR
  name: williamsr_14
  period: 14
  source: close
- indicator: fishertransform
  name: fishertransform_10
  period: 10
  source: close
- indicator: sma
  name: sma_20
  period: 20
  source: close
- indicator: sma
  name: sma_50
  period: 50
  source: close
- indicator: sma
  name: sma_200
  period: 200
  source: close
- indicator: ema
  name: ema_9
  period: 9
  source: close
- indicator: ema
  name: ema_21
  period: 21
  source: close
- indicator: ema
  name: ema_55
  period: 55
  source: close
- indicator: adx
  name: adx_14
  period: 14
  source: close
- indicator: adx
  name: adx_21
  period: 21
  source: close
- indicator: supertrend
  name: supertrend_10
  period: 10
  source: close
- indicator: parabolicsar
  name: parabolicsar_14
  period: 14
  source: close
- indicator: aroon
  name: aroon_25
  period: 25
  source: close
- indicator: bbands
  name: bbands_20_2
  period: 20
  source: close
  std_dev: 2
- indicator: bbands
  name: bbands_50_2
  period: 50
  source: close
  std_dev: 2
- indicator: atr
  name: atr_14
  period: 14
  source: close
- indicator: atr
  name: atr_21
  period: 21
  source: close
- indicator: keltnerchannels
  name: keltnerchannels_20
  period: 20
  source: close
- indicator: bollingerbandwidth
  name: bollingerbandwidth_20
  period: 20
  source: close
- indicator: donchianchannels
  name: donchianchannels_20
  period: 20
  source: close
- indicator: obv
  name: obv_14
  period: 14
  source: close
- indicator: vwap
  name: vwap_14
  period: 14
  source: close
- indicator: mfi
  name: mfi_14
  period: 14
  source: close
- indicator: cmf
  name: cmf_20
  period: 20
  source: close
- indicator: volumeratio
  name: volumeratio_20
  period: 20
  source: close
- indicator: distancefromma
  name: distancefromma_50
  period: 50
  source: close
fuzzy_sets:
  rsi_14:
    extreme_oversold:
      type: triangular
      parameters:
      - 0
      - 10
      - 25
    oversold:
      type: triangular
      parameters:
      - 15
      - 30
      - 40
    neutral_low:
      type: triangular
      parameters:
      - 35
      - 45
      - 55
    neutral_high:
      type: triangular
      parameters:
      - 45
      - 55
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 70
      - 85
    extreme_overbought:
      type: triangular
      parameters:
      - 75
      - 90
      - 100
  rsi_7:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  rsi_21:
    oversold:
      type: triangular
      parameters:
      - 0
      - 25
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
  macd_12_26_9:
    strong_bearish:
      type: triangular
      parameters:
      - -100
      - -50
      - -10
    bearish:
      type: triangular
      parameters:
      - -20
      - -5
      - 0
    neutral:
      type: triangular
      parameters:
      - -5
      - 0
      - 5
    bullish:
      type: triangular
      parameters:
      - 0
      - 5
      - 20
    strong_bullish:
      type: triangular
      parameters:
      - 10
      - 50
      - 100
  macd_5_13_5:
    bearish:
      type: triangular
      parameters:
      - -50
      - -10
      - 0
    neutral:
      type: triangular
      parameters:
      - -5
      - 0
      - 5
    bullish:
      type: triangular
      parameters:
      - 0
      - 10
      - 50
  stochastic_14_3_3:
    oversold:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    neutral:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: triangular
      parameters:
      - 70
      - 85
      - 100
  stochastic_5_3_3:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  adx_14:
    no_trend:
      type: triangular
      parameters:
      - 0
      - 12
      - 25
    weak_trend:
      type: triangular
      parameters:
      - 15
      - 25
      - 35
    moderate_trend:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    strong_trend:
      type: triangular
      parameters:
      - 45
      - 60
      - 75
    very_strong_trend:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  adx_21:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: triangular
      parameters:
      - 40
      - 60
      - 100
  bollingerbands_20_2.0:
    below_lower:
      type: triangular
      parameters:
      - 0.8
      - 0.92
      - 1.0
    lower_middle:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.02
    middle:
      type: triangular
      parameters:
      - 0.96
      - 1.0
      - 1.04
    upper_middle:
      type: triangular
      parameters:
      - 0.98
      - 1.04
      - 1.1
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.08
      - 1.2
  bollingerbands_50_2.0:
    below_lower:
      type: triangular
      parameters:
      - 0.85
      - 0.94
      - 1.0
    middle:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.06
      - 1.15
  sma_20:
    far_below:
      type: triangular
      parameters:
      - 0.8
      - 0.9
      - 0.97
    below:
      type: triangular
      parameters:
      - 0.93
      - 0.97
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.03
      - 1.07
    far_above:
      type: triangular
      parameters:
      - 1.03
      - 1.1
      - 1.2
  sma_50:
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.93
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.07
      - 1.15
  sma_200:
    below:
      type: triangular
      parameters:
      - 0.8
      - 0.9
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.95
      - 1.0
      - 1.05
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.1
      - 1.25
  ema_9:
    below:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.04
      - 1.1
  ema_21:
    below:
      type: triangular
      parameters:
      - 0.88
      - 0.95
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.12
  ema_55:
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.93
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.96
      - 1.0
      - 1.04
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.07
      - 1.15
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    moderate_volatility:
      type: triangular
      parameters:
      - 1.0
      - 2.0
      - 3.5
    high_volatility:
      type: triangular
      parameters:
      - 3.0
      - 5.0
      - 8.0
    extreme_volatility:
      type: triangular
      parameters:
      - 6.0
      - 10.0
      - 20.0
  atr_21:
    low:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    moderate:
      type: triangular
      parameters:
      - 1.0
      - 2.5
      - 4.0
    high:
      type: triangular
      parameters:
      - 3.5
      - 6.0
      - 15.0
  cci:
    extreme_oversold:
      type: triangular
      parameters:
      - -300
      - -200
      - -100
    oversold:
      type: triangular
      parameters:
      - -150
      - -100
      - -50
    neutral:
      type: triangular
      parameters:
      - -75
      - 0
      - 75
    overbought:
      type: triangular
      parameters:
      - 50
      - 100
      - 150
    extreme_overbought:
      type: triangular
      parameters:
      - 100
      - 200
      - 300
  momentum:
    strong_bearish:
      type: triangular
      parameters:
      - -20
      - -10
      - -2
    bearish:
      type: triangular
      parameters:
      - -5
      - -2
      - 0
    neutral:
      type: triangular
      parameters:
      - -2
      - 0
      - 2
    bullish:
      type: triangular
      parameters:
      - 0
      - 2
      - 5
    strong_bullish:
      type: triangular
      parameters:
      - 2
      - 10
      - 20
  roc:
    strong_decline:
      type: triangular
      parameters:
      - -15
      - -8
      - -3
    decline:
      type: triangular
      parameters:
      - -5
      - -2
      - 0
    neutral:
      type: triangular
      parameters:
      - -2
      - 0
      - 2
    advance:
      type: triangular
      parameters:
      - 0
      - 2
      - 5
    strong_advance:
      type: triangular
      parameters:
      - 3
      - 8
      - 15
  williamsR:
    oversold:
      type: triangular
      parameters:
      - -100
      - -85
      - -70
    neutral:
      type: triangular
      parameters:
      - -70
      - -50
      - -30
    overbought:
      type: triangular
      parameters:
      - -30
      - -15
      - 0
  mfi:
    oversold:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    neutral_low:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    neutral_high:
      type: triangular
      parameters:
      - 45
      - 60
      - 75
    overbought:
      type: triangular
      parameters:
      - 70
      - 85
      - 100
  cmf:
    strong_distribution:
      type: triangular
      parameters:
      - -0.3
      - -0.15
      - -0.05
    distribution:
      type: triangular
      parameters:
      - -0.1
      - -0.05
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.05
      - 0.0
      - 0.05
    accumulation:
      type: triangular
      parameters:
      - 0.0
      - 0.05
      - 0.1
    strong_accumulation:
      type: triangular
      parameters:
      - 0.05
      - 0.15
      - 0.3
  fishertransform_10_3:
    extreme_oversold:
      type: triangular
      parameters:
      - -4.0
      - -3.0
      - -2.0
    oversold:
      type: triangular
      parameters:
      - -2.5
      - -1.5
      - -0.5
    neutral:
      type: triangular
      parameters:
      - -1.0
      - 0.0
      - 1.0
    overbought:
      type: triangular
      parameters:
      - 0.5
      - 1.5
      - 2.5
    extreme_overbought:
      type: triangular
      parameters:
      - 2.0
      - 3.0
      - 4.0
  aroon:
    strong_down:
      type: triangular
      parameters:
      - -100
      - -75
      - -40
    down:
      type: triangular
      parameters:
      - -60
      - -30
      - 0
    neutral:
      type: triangular
      parameters:
      - -30
      - 0
      - 30
    up:
      type: triangular
      parameters:
      - 0
      - 30
      - 60
    strong_up:
      type: triangular
      parameters:
      - 40
      - 75
      - 100
  bollingerbandwidth:
    squeeze:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    narrow:
      type: triangular
      parameters:
      - 0.03
      - 0.06
      - 0.1
    normal:
      type: triangular
      parameters:
      - 0.08
      - 0.12
      - 0.18
    wide:
      type: triangular
      parameters:
      - 0.15
      - 0.25
      - 0.4
    extreme:
      type: triangular
      parameters:
      - 0.35
      - 0.5
      - 1.0
  volumeratio:
    low_volume:
      type: triangular
      parameters:
      - 0.0
      - 0.4
      - 0.7
    average_volume:
      type: triangular
      parameters:
      - 0.6
      - 1.0
      - 1.4
    high_volume:
      type: triangular
      parameters:
      - 1.2
      - 1.8
      - 2.5
    extreme_volume:
      type: triangular
      parameters:
      - 2.0
      - 3.5
      - 10.0
  distancefromma:
    far_below:
      type: triangular
      parameters:
      - -0.15
      - -0.08
      - -0.03
    below:
      type: triangular
      parameters:
      - -0.05
      - -0.02
      - 0.0
    at_ma:
      type: triangular
      parameters:
      - -0.02
      - 0.0
      - 0.02
    above:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    far_above:
      type: triangular
      parameters:
      - 0.03
      - 0.08
      - 0.15
  vwap:
    below:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.0
    at_vwap:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.04
      - 1.1
model:
  type: mlp
  architecture:
    hidden_layers:
    - 256
    - 128
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: true
    lookback_periods: 5
    scale_features: true
  training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 150
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
  filters:
    min_signal_separation: 3
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 15
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
