name: mtf_forex_neural
description: Multi-timeframe forex neural strategy using 30+ indicators across momentum,
  trend, volatility, and volume. Trained on major forex pairs with 5m entry signals,
  1h intermediate trend, and 1d major trend context.
version: '3.0'
hypothesis: Forex markets exhibit consistent multi-timeframe patterns across major
  pairs. By combining momentum oscillators for entry timing, trend indicators for
  directional bias, volatility measures for regime adaptation, and volume proxies
  for institutional flow, the neural network can learn generalizable trading patterns
  that work across different currency pairs and market conditions.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
    - AUDUSD
    - EURJPY
    - EURGBP
    - AUDJPY
  timeframes:
    mode: multi_timeframe
    list:
    - 1h
    - 1d
    base_timeframe: 1h
  history_required: 300
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: multi_timeframe
    supported:
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
  rsi_7:
    type: rsi
    period: 7
    source: close
  rsi_21:
    type: rsi
    period: 21
    source: close
  macd_12_26_9:
    type: macd
    fast_period: 12
    slow_period: 26
    signal_period: 9
    source: close
  macd_5_13_5:
    type: macd
    fast_period: 5
    slow_period: 13
    signal_period: 5
    source: close
  stoch_14_3_3:
    type: stoch
    k_period: 14
    d_period: 3
    smooth_k: 3
  stoch_5_3_3:
    type: stoch
    k_period: 5
    d_period: 3
    smooth_k: 3
  cci_20:
    type: cci
    period: 20
  momentum_10:
    type: momentum
    period: 10
    source: close
  roc_12:
    type: roc
    period: 12
    source: close
  williamsr_14:
    type: williamsr
    period: 14
  fishertransform_10_3:
    type: fishertransform
    period: 10
    smoothing: 3
  sma_20:
    type: sma
    period: 20
    source: close
  sma_50:
    type: sma
    period: 50
    source: close
  sma_200:
    type: sma
    period: 200
    source: close
  ema_9:
    type: ema
    period: 9
    source: close
  ema_21:
    type: ema
    period: 21
    source: close
  ema_55:
    type: ema
    period: 55
    source: close
  adx_14:
    type: adx
    period: 14
  adx_21:
    type: adx
    period: 21
  supertrend_10_3_0:
    type: supertrend
    period: 10
    multiplier: 3.0
  parabolicsar_0_02_0_02_0_2:
    type: parabolicsar
    initial_af: 0.02
    step_af: 0.02
    max_af: 0.2
  aroon_25_False:
    type: aroon
    period: 25
  bbands_20_2:
    type: bbands
    period: 20
    source: close
    multiplier: 2
  bbands_50_2:
    type: bbands
    period: 50
    source: close
    multiplier: 2
  atr_14:
    type: atr
    period: 14
  atr_21:
    type: atr
    period: 21
  keltnerchannels_20_10_2_0:
    type: keltnerchannels
    period: 20
    atr_period: 10
    multiplier: 2.0
  bollingerbandwidth_20_2_0:
    type: bollingerbandwidth
    period: 20
  donchianchannels_20_True:
    type: donchianchannels
    period: 20
  obv:
    type: obv
  vwap_20_True:
    type: vwap
  mfi_14:
    type: mfi
    period: 14
  cmf_20:
    type: cmf
    period: 20
  volumeratio_20:
    type: volumeratio
    period: 20
  distancefromma_50_SMA:
    type: distancefromma
    period: 50
    source: close
fuzzy_sets:
  rsi_14:
    extreme_oversold:
      type: triangular
      parameters:
      - 0
      - 10
      - 25
    oversold:
      type: triangular
      parameters:
      - 15
      - 30
      - 40
    neutral_low:
      type: triangular
      parameters:
      - 35
      - 45
      - 55
    neutral_high:
      type: triangular
      parameters:
      - 45
      - 55
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 70
      - 85
    extreme_overbought:
      type: triangular
      parameters:
      - 75
      - 90
      - 100
    indicator: rsi_14
  rsi_7:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: rsi_7
  rsi_21:
    oversold:
      type: triangular
      parameters:
      - 0
      - 25
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
    indicator: rsi_21
  macd_12_26_9:
    strong_bearish:
      type: triangular
      parameters:
      - -100
      - -50
      - -10
    bearish:
      type: triangular
      parameters:
      - -20
      - -5
      - 0
    neutral:
      type: triangular
      parameters:
      - -5
      - 0
      - 5
    bullish:
      type: triangular
      parameters:
      - 0
      - 5
      - 20
    strong_bullish:
      type: triangular
      parameters:
      - 10
      - 50
      - 100
    indicator: macd_12_26_9
  macd_5_13_5:
    bearish:
      type: triangular
      parameters:
      - -50
      - -10
      - 0
    neutral:
      type: triangular
      parameters:
      - -5
      - 0
      - 5
    bullish:
      type: triangular
      parameters:
      - 0
      - 10
      - 50
    indicator: macd_5_13_5
  stoch_14_3_3:
    oversold:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    neutral:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: triangular
      parameters:
      - 70
      - 85
      - 100
    indicator: stoch_14_3_3
  stoch_5_3_3:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: stoch_5_3_3
  adx_14:
    no_trend:
      type: triangular
      parameters:
      - 0
      - 12
      - 25
    weak_trend:
      type: triangular
      parameters:
      - 15
      - 25
      - 35
    moderate_trend:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    strong_trend:
      type: triangular
      parameters:
      - 45
      - 60
      - 75
    very_strong_trend:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: adx_14
  adx_21:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: triangular
      parameters:
      - 40
      - 60
      - 100
    indicator: adx_21
  bbands_20_2:
    below_lower:
      type: triangular
      parameters:
      - 0.8
      - 0.92
      - 1.0
    lower_middle:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.02
    middle:
      type: triangular
      parameters:
      - 0.96
      - 1.0
      - 1.04
    upper_middle:
      type: triangular
      parameters:
      - 0.98
      - 1.04
      - 1.1
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.08
      - 1.2
    indicator: bbands_20_2
  bbands_50_2:
    below_lower:
      type: triangular
      parameters:
      - 0.85
      - 0.94
      - 1.0
    middle:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.06
      - 1.15
    indicator: bbands_50_2
  sma_20:
    input_transform:
      type: price_ratio
      reference: close
    far_below:
      type: triangular
      parameters:
      - 0.8
      - 0.9
      - 0.97
    below:
      type: triangular
      parameters:
      - 0.93
      - 0.97
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.03
      - 1.07
    far_above:
      type: triangular
      parameters:
      - 1.03
      - 1.1
      - 1.2
    indicator: sma_20
  sma_50:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.93
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.07
      - 1.15
    indicator: sma_50
  sma_200:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.8
      - 0.9
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.95
      - 1.0
      - 1.05
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.1
      - 1.25
    indicator: sma_200
  ema_9:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.04
      - 1.1
    indicator: ema_9
  ema_21:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.88
      - 0.95
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.97
      - 1.0
      - 1.03
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.12
    indicator: ema_21
  ema_55:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.93
      - 1.0
    at_ma:
      type: triangular
      parameters:
      - 0.96
      - 1.0
      - 1.04
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.07
      - 1.15
    indicator: ema_55
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    moderate_volatility:
      type: triangular
      parameters:
      - 1.0
      - 2.0
      - 3.5
    high_volatility:
      type: triangular
      parameters:
      - 3.0
      - 5.0
      - 8.0
    extreme_volatility:
      type: triangular
      parameters:
      - 6.0
      - 10.0
      - 20.0
    indicator: atr_14
  atr_21:
    low:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    moderate:
      type: triangular
      parameters:
      - 1.0
      - 2.5
      - 4.0
    high:
      type: triangular
      parameters:
      - 3.5
      - 6.0
      - 15.0
    indicator: atr_21
  cci_20:
    extreme_oversold:
      type: triangular
      parameters:
      - -300
      - -200
      - -100
    oversold:
      type: triangular
      parameters:
      - -150
      - -100
      - -50
    neutral:
      type: triangular
      parameters:
      - -75
      - 0
      - 75
    overbought:
      type: triangular
      parameters:
      - 50
      - 100
      - 150
    extreme_overbought:
      type: triangular
      parameters:
      - 100
      - 200
      - 300
    indicator: cci_20
  momentum_10:
    strong_bearish:
      type: triangular
      parameters:
      - -20
      - -10
      - -2
    bearish:
      type: triangular
      parameters:
      - -5
      - -2
      - 0
    neutral:
      type: triangular
      parameters:
      - -2
      - 0
      - 2
    bullish:
      type: triangular
      parameters:
      - 0
      - 2
      - 5
    strong_bullish:
      type: triangular
      parameters:
      - 2
      - 10
      - 20
    indicator: momentum_10
  roc_12:
    strong_decline:
      type: triangular
      parameters:
      - -15
      - -8
      - -3
    decline:
      type: triangular
      parameters:
      - -5
      - -2
      - 0
    neutral:
      type: triangular
      parameters:
      - -2
      - 0
      - 2
    advance:
      type: triangular
      parameters:
      - 0
      - 2
      - 5
    strong_advance:
      type: triangular
      parameters:
      - 3
      - 8
      - 15
    indicator: roc_12
  williamsr_14:
    oversold:
      type: triangular
      parameters:
      - -100
      - -85
      - -70
    neutral:
      type: triangular
      parameters:
      - -70
      - -50
      - -30
    overbought:
      type: triangular
      parameters:
      - -30
      - -15
      - 0
    indicator: williamsr_14
  mfi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    neutral_low:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    neutral_high:
      type: triangular
      parameters:
      - 45
      - 60
      - 75
    overbought:
      type: triangular
      parameters:
      - 70
      - 85
      - 100
    indicator: mfi_14
  cmf_20:
    strong_distribution:
      type: triangular
      parameters:
      - -0.3
      - -0.15
      - -0.05
    distribution:
      type: triangular
      parameters:
      - -0.1
      - -0.05
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.05
      - 0.0
      - 0.05
    accumulation:
      type: triangular
      parameters:
      - 0.0
      - 0.05
      - 0.1
    strong_accumulation:
      type: triangular
      parameters:
      - 0.05
      - 0.15
      - 0.3
    indicator: cmf_20
  fishertransform_10_3:
    extreme_oversold:
      type: triangular
      parameters:
      - -4.0
      - -3.0
      - -2.0
    oversold:
      type: triangular
      parameters:
      - -2.5
      - -1.5
      - -0.5
    neutral:
      type: triangular
      parameters:
      - -1.0
      - 0.0
      - 1.0
    overbought:
      type: triangular
      parameters:
      - 0.5
      - 1.5
      - 2.5
    extreme_overbought:
      type: triangular
      parameters:
      - 2.0
      - 3.0
      - 4.0
    indicator: fishertransform_10_3
  aroon_25_False:
    strong_down:
      type: triangular
      parameters:
      - -100
      - -75
      - -40
    down:
      type: triangular
      parameters:
      - -60
      - -30
      - 0
    neutral:
      type: triangular
      parameters:
      - -30
      - 0
      - 30
    up:
      type: triangular
      parameters:
      - 0
      - 30
      - 60
    strong_up:
      type: triangular
      parameters:
      - 40
      - 75
      - 100
    indicator: aroon_25_False
  bollingerbandwidth_20_2_0:
    squeeze:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    narrow:
      type: triangular
      parameters:
      - 0.03
      - 0.06
      - 0.1
    normal:
      type: triangular
      parameters:
      - 0.08
      - 0.12
      - 0.18
    wide:
      type: triangular
      parameters:
      - 0.15
      - 0.25
      - 0.4
    extreme:
      type: triangular
      parameters:
      - 0.35
      - 0.5
      - 1.0
    indicator: bollingerbandwidth_20_2_0
  volumeratio_20:
    low_volume:
      type: triangular
      parameters:
      - 0.0
      - 0.4
      - 0.7
    average_volume:
      type: triangular
      parameters:
      - 0.6
      - 1.0
      - 1.4
    high_volume:
      type: triangular
      parameters:
      - 1.2
      - 1.8
      - 2.5
    extreme_volume:
      type: triangular
      parameters:
      - 2.0
      - 3.5
      - 10.0
    indicator: volumeratio_20
  distancefromma_50_SMA:
    far_below:
      type: triangular
      parameters:
      - -0.15
      - -0.08
      - -0.03
    below:
      type: triangular
      parameters:
      - -0.05
      - -0.02
      - 0.0
    at_ma:
      type: triangular
      parameters:
      - -0.02
      - 0.0
      - 0.02
    above:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    far_above:
      type: triangular
      parameters:
      - 0.03
      - 0.08
      - 0.15
    indicator: distancefromma_50_SMA
  vwap_20_True:
    below:
      type: triangular
      parameters:
      - 0.9
      - 0.96
      - 1.0
    at_vwap:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.04
      - 1.1
    indicator: vwap_20_True
model:
  type: mlp
  architecture:
    hidden_layers:
    - 256
    - 128
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: true
    lookback_periods: 5
    scale_features: true
  training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 150
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
  filters:
    min_signal_separation: 3
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 15
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
- fuzzy_set: rsi_7
  timeframes: all
- fuzzy_set: rsi_21
  timeframes: all
- fuzzy_set: macd_12_26_9
  timeframes: all
- fuzzy_set: macd_5_13_5
  timeframes: all
- fuzzy_set: stoch_14_3_3
  timeframes: all
- fuzzy_set: stoch_5_3_3
  timeframes: all
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: adx_21
  timeframes: all
- fuzzy_set: bbands_20_2
  timeframes: all
- fuzzy_set: bbands_50_2
  timeframes: all
- fuzzy_set: sma_20
  timeframes: all
- fuzzy_set: sma_50
  timeframes: all
- fuzzy_set: sma_200
  timeframes: all
- fuzzy_set: ema_9
  timeframes: all
- fuzzy_set: ema_21
  timeframes: all
- fuzzy_set: ema_55
  timeframes: all
- fuzzy_set: atr_14
  timeframes: all
- fuzzy_set: atr_21
  timeframes: all
- fuzzy_set: cci_20
  timeframes: all
- fuzzy_set: momentum_10
  timeframes: all
- fuzzy_set: roc_12
  timeframes: all
- fuzzy_set: williamsr_14
  timeframes: all
- fuzzy_set: mfi_14
  timeframes: all
- fuzzy_set: cmf_20
  timeframes: all
- fuzzy_set: fishertransform_10_3
  timeframes: all
- fuzzy_set: aroon_25_False
  timeframes: all
- fuzzy_set: bollingerbandwidth_20_2_0
  timeframes: all
- fuzzy_set: volumeratio_20
  timeframes: all
- fuzzy_set: distancefromma_50_SMA
  timeframes: all
- fuzzy_set: vwap_20_True
  timeframes: all
