name: neuro_mean_reversion
description: Neural network trained on RSI/MACD fuzzy outputs for mean reversion
version: '2.0'
hypothesis: RSI oversold/overbought conditions combined with MACD momentum confirmation create profitable mean reversion opportunities
  in trending markets
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - AAPL
    - MSFT
    - GOOGL
  timeframes:
    mode: multi_timeframe
    list:
    - 1h
    - 4h
    - 1d
    base_timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: group_restricted
  target_timeframes:
    mode: multi_timeframe
    supported:
    - 1h
    - 4h
    - 1d
indicators:
- indicator: rsi
  name: rsi_14
  period: 14
  source: close
- indicator: macd
  name: macd_12_26_9
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: close
fuzzy_sets:
  rsi:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
model:
  type: mlp
  architecture:
    hidden_layers:
    - 50
    - 25
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
