# High Win-Rate Conservative Strategy
name: "rsi_mean_reversion_ma"
description: "RSI(2) mean reversion filtered by 200-SMA for trend direction"
version: "1.0"

# Data requirements
data:
  symbols: ["SPY", "QQQ", "EURUSD", "GBPUSD"]
  timeframes: ["15m", "1h", "4h"]
  history_required: 250  # Need 200 SMA + buffer

# Technical indicators configuration
indicators:
  - name: rsi
    period: 2      # Ultra-sensitive RSI for mean reversion
    source: close
  - name: sma
    period: 200    # Long-term trend filter
    source: close
  - name: atr
    period: 14     # For dynamic stop loss

# Fuzzy logic configuration
fuzzy_sets:
  rsi:
    very_oversold:
      type: triangular
      parameters: [0, 5, 15]
    oversold:
      type: triangular
      parameters: [10, 20, 30]
    neutral:
      type: triangular
      parameters: [25, 50, 75]
    overbought:
      type: triangular
      parameters: [70, 80, 90]
    very_overbought:
      type: triangular
      parameters: [85, 95, 100]
  
  price_to_sma:
    far_below:
      type: triangular
      parameters: [0.90, 0.95, 0.98]
    below:
      type: triangular
      parameters: [0.97, 0.99, 1.00]
    at:
      type: triangular
      parameters: [0.99, 1.00, 1.01]
    above:
      type: triangular
      parameters: [1.00, 1.01, 1.03]
    far_above:
      type: triangular
      parameters: [1.02, 1.05, 1.10]

# Neural network configuration
model:
  type: "mlp"
  architecture:
    hidden_layers: [20, 10, 5]  # Simpler for conservative strategy
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.15
  
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 150
    optimizer: "adam"
    weight_decay: 0.0001
    
    lr_scheduler:
      type: "reduce_on_plateau"
      factor: 0.5
      patience: 20
    
    early_stopping:
      patience: 25
      monitor: "val_loss"
      min_delta: 0.0001
  
  features:
    include_price_context: true
    include_volume_context: false  # Not needed for this strategy
    lookback_periods: 2           # Recent RSI behavior
    scale_features: true
    scaling_method: "standard"

# Decision logic configuration
decisions:
  output_format: "classification"
  confidence_threshold: 0.7      # Higher for conservative approach
  position_awareness: true
  
  filters:
    min_signal_separation: 3     # Avoid overtrading
    volume_filter: false

# Specific strategy rules
orchestrator:
  max_position_size: 0.90
  signal_cooldown: 3
  
  # Mean reversion specific
  entry_rules:
    long:
      - rsi_very_oversold: "> 0.7"    # Strong oversold
      - price_to_sma_above: "> 0.5"   # In uptrend
    short:
      - rsi_very_overbought: "> 0.7"  # Strong overbought
      - price_to_sma_below: "> 0.5"   # In downtrend
  
  exit_rules:
    # Exit when RSI normalizes
    close_long:
      - rsi_neutral: "> 0.5"
    close_short:
      - rsi_neutral: "> 0.5"
  
  modes:
    backtest:
      confidence_threshold: 0.65
    paper:
      confidence_threshold: 0.70
    live:
      confidence_threshold: 0.75

# Training configuration
training:
  method: "supervised"
  labels:
    source: "zigzag"
    zigzag_threshold: 0.02     # 2% for mean reversion
    label_lookahead: 10        # Shorter for mean reversion
  
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  
  fitness_metrics:
    primary: "win_rate"        # Focus on high win rate
    secondary: ["sharpe_ratio", "max_drawdown"]

# Risk management
risk_management:
  position_sizing: "fixed_fraction"
  risk_per_trade: 0.015        # 1.5% for conservative
  max_portfolio_risk: 0.06     # 6% total exposure
  
  # Mean reversion specific
  stop_loss:
    type: "atr_based"
    atr_multiplier: 2.0        # Tight stops for mean reversion
  
  take_profit:
    type: "rsi_based"          # Exit on RSI normalization
    target_rsi: 50

# Backtesting configuration
backtesting:
  start_date: "2020-01-01"
  end_date: "2024-01-01"
  initial_capital: 100000
  transaction_costs: 0.0008    # Lower for liquid instruments
  slippage: 0.0003            # Minimal for major pairs
