# === STRATEGY IDENTITY ===
name: "test_multi_full_combined"
description: "Combined multi-symbol and multi-timeframe test - the ultimate complexity test"
version: "2.0"
hypothesis: "Multi-symbol + multi-timeframe infrastructure can handle maximum complexity with 3 symbols across 2 timeframes"

# === STRATEGY SCOPE ===
scope: "universal"

# === TRAINING APPROACH ===
training_data:
  symbols:
    mode: "multi_symbol"
    list: ["EURUSD", "GBPUSD"]  # Two symbols with complete multi-timeframe data
  timeframes:
    mode: "multi_timeframe"
    list: ["1h", "1d"]  # Only use timeframes all symbols have data for
    base_timeframe: "1h"  # Primary signal generation timeframe
  history_required: 200

# === DEPLOYMENT TARGETS ===
deployment:
  target_symbols:
    mode: "universal"
  target_timeframes:
    mode: "multi_timeframe"
    supported: ["1h", "1d"]

# === TECHNICAL INDICATORS ===
indicators:
- name: "rsi"
  period: 14
  source: "close"
- name: "macd"
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: "close"
- name: "sma"
  period: 20
  source: "close"
- name: "BollingerBands"
  period: 20
  multiplier: 2.0
  source: "close"

# === FUZZY LOGIC CONFIGURATION ===
fuzzy_sets:
  rsi:
    oversold:
      type: "triangular"
      parameters: [0, 20, 35]
    neutral:
      type: "triangular"
      parameters: [30, 50, 70]
    overbought:
      type: "triangular"
      parameters: [65, 80, 100]
  sma:
    below:
      type: "triangular"
      parameters: [0.85, 0.95, 1.0]
    neutral:
      type: "triangular"
      parameters: [0.98, 1.0, 1.02]
    above:
      type: "triangular"
      parameters: [1.0, 1.05, 1.15]
  BollingerBands:
    below_lower:
      type: "triangular"
      parameters: [0.85, 0.95, 1.0]
    between_bands:
      type: "triangular"
      parameters: [0.98, 1.0, 1.02]
    above_upper:
      type: "triangular"
      parameters: [1.0, 1.05, 1.15]

# === NEURAL NETWORK MODEL ===
model:
  type: "mlp"
  symbol_embedding_dim: 16  # 16 dimensions for 2 symbols
  architecture:
    hidden_layers: [256, 128, 64]  # Appropriate network for 2 symbols + multi-timeframe
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.4  # Higher dropout to prevent overfitting
  features:
    include_price_context: true  # Include OHLC context
    lookback_periods: 3  # Reduced to manage feature explosion
    scale_features: true
  training:
    learning_rate: 0.0005  # Lower learning rate for stability
    batch_size: 128  # Larger batches for stability
    epochs: 40  # Sufficient for convergence but not overfitting
    optimizer: "adam"

# === DECISION LOGIC ===
decisions:
  output_format: "classification"
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false

# === TRAINING CONFIGURATION ===
training:
  method: "supervised"
  labels:
    source: "zigzag"
    zigzag_threshold: 0.02  # Realistic threshold
    label_lookahead: 12  # Reasonable lookahead
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15