name: test_e2e_local_pull
description: Minimal strategy for E2E testing of pull-based operations
version: '3.0'
hypothesis: Simple RSI strategy for fast testing
scope: symbol_specific
training_data:
  symbols:
    mode: single
    symbol: EURUSD
  timeframes:
    mode: single
    timeframe: 5m
  history_required: 100
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: rsi_14
model:
  type: mlp
  architecture:
    hidden_layers:
    - 25
    - 15
    activation: relu
    output_activation: softmax
    dropout: 0.1
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
