# === STRATEGY IDENTITY ===
name: "test_e2e_local_pull"
description: "Minimal strategy for E2E testing of pull-based operations"
version: "1.0"
hypothesis: "Simple RSI strategy for fast testing"

# === STRATEGY SCOPE ===
scope: "symbol_specific"

# === TRAINING APPROACH ===
training_data:
  symbols:
    mode: "single"
    symbol: "EURUSD"  # Single symbol for fast testing
  timeframes:
    mode: "single"
    timeframe: "5m"  # Single timeframe for fast testing
  history_required: 100  # Minimal history for quick data loading

# === DEPLOYMENT TARGETS ===
deployment:
  target_symbols:
    mode: "training_only"
  target_timeframes:
    mode: "single"
    timeframe: "1h"

# === TECHNICAL INDICATORS ===
indicators:
- name: "rsi"
  feature_id: rsi_14
  period: 14
  source: "close"

# === FUZZY LOGIC CONFIGURATION ===
fuzzy_sets:
  rsi_14:
    oversold:
      type: "triangular"
      parameters: [0, 20, 35]
    neutral:
      type: "triangular"
      parameters: [30, 50, 70]
    overbought:
      type: "triangular"
      parameters: [65, 80, 100]

# === NEURAL NETWORK MODEL ===
model:
  type: "mlp"
  architecture:
    hidden_layers: [25, 15]  # Smaller network for fast training
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.1
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10  # SMALL for fast testing!
    optimizer: "adam"

# === DECISION LOGIC ===
decisions:
  output_format: "classification"
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false

# === TRAINING CONFIGURATION ===
training:
  method: "supervised"
  labels:
    source: "zigzag"
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15