# === STRATEGY IDENTITY ===
name: "trend_momentum"  # Trend-following strategy capturing sustained moves
description: "A strategy combining trend and momentum indicators with customized fuzzy
  sets"                                                                                       # Clear one-line strategy summary
version: "2.1"  # Clean format version for AI agent compatibility
hypothesis: "Strong momentum signals combined with trend confirmation create sustainable
  directional moves with favorable risk-reward ratios"                                                                                         # Core strategy belief being tested

# === STRATEGY SCOPE ===
scope: "symbol_specific"  # Symbol-specific model optimized for single asset characteristics

# === TRAINING APPROACH ===
training_data:  # Data configuration for model training
  symbols:  # Asset selection for cross-market learning
    mode: "single"  # Single-symbol training for asset-specific optimization
    symbol: "AAPL"  # Technology stock with high liquidity and predictable patterns
  timeframes:  # Multi-timeframe analysis configuration
    mode: "single"  # Single timeframe for focused signal generation
    timeframe: "1h"  # Primary signal timeframe balancing noise and responsiveness
  history_required: 200  # Standard history for reliable pattern recognition

# === DEPLOYMENT TARGETS ===
deployment:  # Target configuration for live trading
  target_symbols:  # Which assets can use this trained model
    mode: "training_only"  # Deploy only on assets used in training for consistency
  target_timeframes:  # Supported timeframes for deployment
    mode: "single"  # Single timeframe deployment for focused application
    timeframe: "1h"  # Single target timeframe

# === TECHNICAL INDICATORS ===
indicators:  # Core technical analysis components
- name: "rsi"  # Relative Strength Index for momentum and reversal signals
  feature_id: rsi_14
  period: 14  # Lookback period balancing responsiveness vs stability
  source: "close"  # Price source for calculation consistency
- name: "macd"  # MACD for trend direction and momentum confirmation
  feature_id: macd_12_26_9
  fast_period: 12  # Fast EMA period for responsive signal generation
  slow_period: 26  # Slow EMA period for trend stability
  signal_period: 9  # Signal line period for entry/exit timing
  source: "close"  # Price source for calculation consistency
- name: "stoch"  # Stochastic oscillator for overbought/oversold conditions
  feature_id: stoch_14_3_3
  k_period: 14  # K percent period for stochastic calculation
  d_period: 3  # D smoothing period for stochastic signal
  smooth_k: 3  # K line smoothing period
- name: "adx"  # Average Directional Index for trend strength measurement
  feature_id: adx_14
  period: 14  # Lookback period balancing responsiveness vs stability
- name: "bbands"  # Bollinger Bands for volatility and mean reversion
  feature_id: bbands_20_2
  period: 20  # Lookback period balancing responsiveness vs stability
  multiplier: 2  # Standard deviation multiplier for band width

# === FUZZY LOGIC CONFIGURATION ===
fuzzy_sets:  # Membership functions for indicator interpretation
  adx_14:  # Fuzzy membership functions for ADX interpretation
    weak:  # Low intensity values indicating uncertainty
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [0, 15, 30]  # Triangular membership: left=0, peak=15, right=30
    moderate:  # Medium intensity values indicating normal conditions
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [20, 35, 50]  # Triangular membership: left=20, peak=35, right=50
    strong:  # High intensity values indicating conviction
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [40, 60, 100]  # Triangular membership: left=40, peak=60, right=100
  rsi_14:  # Fuzzy membership functions for RSI interpretation
    oversold:  # Extreme low values indicating potential reversal
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [0, 20, 35]  # Triangular membership: left=0, peak=20, right=35
    neutral:  # Middle range values indicating market balance
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [30, 50, 70]  # Triangular membership: left=30, peak=50, right=70
    overbought:  # Extreme high values indicating potential reversal
      type: "triangular"  # Triangular membership for crisp boundaries
      parameters: [65, 80, 100]  # Triangular membership: left=65, peak=80, right=100

# === NEURAL NETWORK MODEL ===
model:  # Pure fuzzy-neural architecture configuration
  type: "mlp"  # Multi-Layer Perceptron for fuzzy feature processing
  architecture:  # Network topology and activation configuration
    hidden_layers: [50, 25]  # Network topology: 50 -> 25 neurons for optimal complexity
    activation: "relu"  # ReLU activation for fast training and gradient flow
    output_activation: "softmax"  # Softmax for multi-class probability distribution
    dropout: 0.2  # Moderate dropout for balanced regularization
  features:  # Input feature engineering configuration
    include_price_context: false  # Include OHLC price context for market structure awareness
    lookback_periods: 2  # Historical window size for temporal pattern recognition
    scale_features: false  # Feature normalization for stable neural network training
  training:  # Neural network optimization configuration
    learning_rate: 0.001  # Standard learning rate for stable convergence
    batch_size: 32  # Standard batch size balancing stability and memory
    epochs: 100  # Standard training duration for convergence
    optimizer: "adam"  # Adam optimizer for adaptive learning and momentum

# === DECISION LOGIC ===
decisions:  # Trading signal generation rules
  output_format: "classification"  # Discrete buy/sell/hold class predictions
  confidence_threshold: 0.6  # Moderate confidence for balanced signal quality
  position_awareness: true  # Consider existing positions for intelligent signal filtering
  filters:  # Signal quality and timing filters
    min_signal_separation: 4  # Minimum 4 periods between signals to prevent overtrading
    volume_filter: false  # Accept signals regardless of volume conditions

# === TRAINING CONFIGURATION ===
training:  # Model training methodology and evaluation
  method: "supervised"  # Supervised learning with labeled historical data
  labels:  # Target generation for supervised learning
    source: "zigzag"  # ZigZag-based labels identifying significant price swings
    zigzag_threshold: 0.03  # Minimum 3.0% price swing for signal significance
    label_lookahead: 20  # Look 20 periods ahead for target value determination
  data_split:  # Train/validation/test split configuration
    train: 0.7  # Training data (70%) for model learning
    validation: 0.15  # Validation data (15%) for hyperparameter tuning
    test: 0.15  # Test data (15%) for unbiased performance evaluation
