name: trend_momentum
description: A strategy combining trend and momentum indicators with customized fuzzy sets
version: '2.0'
hypothesis: Strong momentum signals combined with trend confirmation create sustainable directional moves with favorable risk-reward
  ratios
scope: symbol_specific
training_data:
  symbols:
    mode: single
    symbol: AAPL
  timeframes:
    mode: single
    timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
- indicator: rsi
  name: rsi_14
  period: 14
  source: close
- indicator: macd
  name: macd_12_26_9
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: close
- indicator: stoch
  name: stoch_3_14
  k_period: 14
  d_period: 3
  source: close
- indicator: adx
  name: adx_14
  period: 14
  source: close
- indicator: bbands
  name: bbands_20_2
  period: 20
  source: close
  std_dev: 2
fuzzy_sets:
  adx:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: triangular
      parameters:
      - 40
      - 60
      - 100
  rsi:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
model:
  type: mlp
  architecture:
    hidden_layers:
    - 50
    - 25
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: false
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
