name: trend_momentum
description: A strategy combining trend and momentum indicators with customized fuzzy
  sets
version: '3.0'
hypothesis: Strong momentum signals combined with trend confirmation create sustainable
  directional moves with favorable risk-reward ratios
scope: symbol_specific
training_data:
  symbols:
    mode: single
    symbol: AAPL
  timeframes:
    mode: single
    timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
  macd_12_26_9:
    type: macd
    fast_period: 12
    slow_period: 26
    signal_period: 9
    source: close
  stoch_14_3_3:
    type: stoch
    k_period: 14
    d_period: 3
    smooth_k: 3
  adx_14:
    type: adx
    period: 14
  bbands_20_2:
    type: bbands
    period: 20
    multiplier: 2
fuzzy_sets:
  adx_14:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 30
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: triangular
      parameters:
      - 40
      - 60
      - 100
    indicator: adx_14
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: rsi_14
model:
  type: mlp
  architecture:
    hidden_layers:
    - 50
    - 25
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: false
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: rsi_14
  timeframes: all
