backtesting:
  end_date: '2024-01-01'
  initial_capital: 100000
  slippage: 0.0005
  start_date: '2020-01-01'
  transaction_costs: 0.001
decisions:
  confidence_threshold: 0.6
  filters:
    min_signal_separation: 4
    volume_filter: false
  output_format: classification
  position_awareness: true
description: A strategy combining trend and momentum indicators with customized fuzzy
  sets
fuzzy_sets:
  adx:
    moderate:
    - 20
    - 35
    - 50
    strong:
    - 40
    - 60
    - 100
    weak:
    - 0
    - 15
    - 30
  bbands:
    lower:
    - -100
    - -2
    - -0.5
    middle:
    - -1
    - 0
    - 1
    upper:
    - 0.5
    - 2
    - 100
  rsi:
    neutral:
    - 30
    - 50
    - 70
    overbought:
    - 65
    - 80
    - 100
    oversold:
    - 0
    - 20
    - 35
  stoch:
    high:
    - 60
    - 80
    - 100
    low:
    - 0
    - 20
    - 40
    mid:
    - 30
    - 50
    - 70
indicators:
- name: rsi
  period: 14
  source: close
- fast_period: 12
  name: macd
  signal_period: 9
  slow_period: 26
  source: close
- d_period: 3
  k_period: 14
  name: stoch
  source: close
- name: adx
  period: 14
  source: close
- name: bbands
  period: 20
  source: close
  std_dev: 2
model:
  architecture:
    activation: relu
    dropout: 0.2
    hidden_layers:
    - 20
    - 10
    output_activation: softmax
  features:
    include_price_context: true
    include_raw_indicators: false
    include_volume_context: false
    lookback_periods: 3
    scale_features: true
    scaling_method: standard
  hidden_layers:
  - 20
  - 10
  input_size: 12
  output_size: 2
  training:
    batch_size: 32
    early_stopping:
      min_delta: 0.0001
      monitor: val_loss
      patience: 15
    epochs: 100
    learning_rate: 0.001
    optimizer: adam
    weight_decay: 0.0001
  type: mlp
name: neuro_trend_momentum_strategy
orchestrator:
  max_position_size: 0.95
  modes:
    backtest:
      confidence_threshold: 0.6
    live:
      confidence_threshold: 0.7
      require_confirmation: true
    paper:
      confidence_threshold: 0.65
  signal_cooldown: 4
risk_management:
  max_portfolio_risk: 0.1
  position_sizing: fixed_fraction
  risk_per_trade: 0.02
training:
  data_split:
    test: 0.15
    train: 0.7
    validation: 0.15
  fitness_metrics:
    primary: accuracy
    secondary:
    - precision
    - recall
    - f1_score
  labels:
    label_lookahead: 20
    source: zigzag
    zigzag_threshold: 0.05
  method: supervised
version: 1.0.neuro
