name: universal_generalization_model
description: Universal model trained for cross-symbol generalization testing
version: '2.0'
hypothesis: Universal technical patterns can generalize across forex symbols
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
  timeframes:
    mode: single
    timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
- indicator: rsi
  name: rsi_14
  period: 14
  source: close
- indicator: macd
  name: macd_12_26_9
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: close
- indicator: sma
  name: sma_20
  period: 20
  source: close
- indicator: BollingerBands
  name: bollingerbands_2_20
  period: 20
  multiplier: 2.0
  source: close
fuzzy_sets:
  rsi:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  sma:
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.95
      - 1.0
    neutral:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.15
  BollingerBands:
    below_lower:
      type: triangular
      parameters:
      - 0.85
      - 0.95
      - 1.0
    between_bands:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.15
model:
  type: mlp
  symbol_embedding_dim: 16
  architecture:
    hidden_layers:
    - 128
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: true
    lookback_periods: 5
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 40
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.02
    label_lookahead: 12
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
