name: universal_generalization_model
description: Universal model trained for cross-symbol generalization testing
version: '3.0'
hypothesis: Universal technical patterns can generalize across forex symbols
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
  timeframes:
    mode: single
    timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
  macd_12_26_9:
    type: macd
    fast_period: 12
    slow_period: 26
    signal_period: 9
    source: close
  sma_20:
    type: sma
    period: 20
    source: close
  bbands_20_2_0:
    type: bbands
    period: 20
    multiplier: 2.0
    source: close
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: rsi_14
  sma_20:
    input_transform:
      type: price_ratio
      reference: close
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.95
      - 1.0
    neutral:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.15
    indicator: sma_20
  bbands_20_2_0:
    below_lower:
      type: triangular
      parameters:
      - 0.85
      - 0.95
      - 1.0
    between_bands:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above_upper:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.15
    indicator: bbands_20_2_0
model:
  type: mlp
  symbol_embedding_dim: 16
  architecture:
    hidden_layers:
    - 128
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: true
    lookback_periods: 5
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 40
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.02
    label_lookahead: 12
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
- fuzzy_set: sma_20
  timeframes: all
- fuzzy_set: bbands_20_2_0
  timeframes: all
