name: universal_zero_shot_model
description: Universal neural model with zero-shot generalization to unseen symbols
version: '2.0'
hypothesis: Symbol-agnostic features enable universal pattern recognition across any asset
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
  timeframes:
    mode: single
    timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    timeframe: 1h
indicators:
- indicator: rsi
  name: rsi_14
  period: 14
  source: close
- indicator: macd
  name: macd_12_26_9
  fast_period: 12
  slow_period: 26
  signal_period: 9
  source: close
- indicator: sma
  name: sma_20
  period: 20
  source: close
fuzzy_sets:
  rsi:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  sma:
    below:
      type: triangular
      parameters:
      - 0.85
      - 0.95
      - 1.0
    neutral:
      type: triangular
      parameters:
      - 0.98
      - 1.0
      - 1.02
    above:
      type: triangular
      parameters:
      - 1.0
      - 1.05
      - 1.15
model:
  type: mlp
  architecture:
    hidden_layers:
    - 128
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: true
    lookback_periods: 5
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 40
    optimizer: adam
  input_size: 36
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.02
    label_lookahead: 12
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
