name: v15_test_analytics
description: Minimal test strategy to validate TrainingAnalyzer output
version: '3.0'
hypothesis: RSI oversold/overbought conditions create predictable mean reversion opportunities
scope: single_symbol
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 100
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 30
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 70
      - 100
    indicator: rsi_14
model:
  type: mlp
  architecture:
    hidden_layers:
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 1
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10
    optimizer: adam
    analytics:
      enabled: true
      export_csv: true
      export_json: true
      export_alerts: true
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  date_range:
    start: '2023-01-01'
    end: '2023-06-30'
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
