name: v15_williams_stochastic_cmf
description: 'v1.5 experiment: Williams + Stochastic + CMF - oscillators with money
  flow'
version: '3.0'
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 200
indicators:
  williams_14:
    type: williams_r
    period: 14
    source: close
  stochastic_14:
    type: stochastic
    k_period: 14
    d_period: 3
    source: close
  cmf_20:
    type: cmf
    period: 20
fuzzy_sets:
  williams_14:
    oversold:
      type: triangular
      parameters:
      - -100
      - -80
      - -60
    neutral:
      type: triangular
      parameters:
      - -65
      - -50
      - -35
    overbought:
      type: triangular
      parameters:
      - -40
      - -20
      - 0
    indicator: williams_14
  stochastic_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 30
    neutral:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: triangular
      parameters:
      - 70
      - 80
      - 100
    indicator: stochastic_14
  cmf_20:
    selling:
      type: triangular
      parameters:
      - -1
      - -0.3
      - -0.05
    neutral:
      type: triangular
      parameters:
      - -0.1
      - 0
      - 0.1
    buying:
      type: triangular
      parameters:
      - 0.05
      - 0.3
      - 1
    indicator: cmf_20
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001
    analytics:
      enabled: true
      export_csv: true
      export_json: true
      export_alerts: true
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  date_range:
    start: '2015-01-01'
    end: '2023-12-31'
nn_inputs:
- fuzzy_set: williams_14
  timeframes: all
- fuzzy_set: stochastic_14
  timeframes: all
- fuzzy_set: cmf_20
  timeframes: all
