name: v15_rsi_mfi
description: 'v1.5 experiment: RSI + MFI - price momentum with volume'
version: '3.0'
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 200
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
  mfi_14:
    type: mfi
    period: 14
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 30
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 70
      - 100
    indicator: rsi_14
  mfi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 30
      - 40
    neutral:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    overbought:
      type: triangular
      parameters:
      - 60
      - 70
      - 100
    indicator: mfi_14
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001
    analytics:
      enabled: true
      export_csv: true
      export_json: true
      export_alerts: true
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  date_range:
    start: '2015-01-01'
    end: '2023-12-31'
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
- fuzzy_set: mfi_14
  timeframes: all
