name: v15_adx_aroon
description: 'v1.5 experiment: ADX + Aroon - trend strength with timing'
version: '3.0'
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 200
indicators:
  adx_14:
    type: adx
    period: 14
  aroon_25:
    type: aroon
    period: 25
fuzzy_sets:
  ADX_14:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: triangular
      parameters:
      - 45
      - 60
      - 100
    indicator: adx_14
  aroon_up_25:
    weak:
      type: triangular
      parameters:
      - 0
      - 25
      - 40
    moderate:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    strong:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
    indicator: aroon_25
  aroon_down_25:
    weak:
      type: triangular
      parameters:
      - 0
      - 25
      - 40
    moderate:
      type: triangular
      parameters:
      - 35
      - 50
      - 65
    strong:
      type: triangular
      parameters:
      - 60
      - 75
      - 100
    indicator: aroon_25
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001
    analytics:
      enabled: true
      export_csv: true
      export_json: true
      export_alerts: true
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  date_range:
    start: '2015-01-01'
    end: '2023-12-31'
nn_inputs:
- fuzzy_set: ADX_14
  timeframes: all
- fuzzy_set: aroon_up_25
  timeframes: all
- fuzzy_set: aroon_down_25
  timeframes: all
