# =============================================================================
# V3 STRATEGY EXAMPLE: Multiple Indicators
# =============================================================================
# Combines multiple indicators (RSI + ADX) for richer signal generation.
# Demonstrates how to define multiple indicators and fuzzy sets.
#
# Use case: Combining momentum and trend strength indicators
# =============================================================================

name: v3_multi_indicator_example
version: "3.0"
description: RSI momentum with ADX trend strength filter

training_data:
  symbols:
    mode: single
    symbol: EURUSD
  timeframes:
    mode: single
    timeframe: "1h"
  history_required: 200

# ---------------------------------------------------------------------------
# MULTIPLE INDICATORS
# ---------------------------------------------------------------------------
indicators:
  # Momentum indicator
  rsi_14:
    type: rsi
    period: 14
    source: close

  # Trend strength indicator
  # Note: ADX produces multiple outputs (ADX, DI+, DI-)
  adx_14:
    type: adx
    period: 14

# ---------------------------------------------------------------------------
# FUZZY SETS FOR EACH INDICATOR
# ---------------------------------------------------------------------------
fuzzy_sets:
  # RSI interpretation
  rsi_14:
    indicator: rsi_14
    oversold:
      type: triangular
      parameters: [0, 30, 40]
    neutral:
      type: triangular
      parameters: [35, 50, 65]
    overbought:
      type: triangular
      parameters: [60, 70, 100]

  # ADX interpretation (trend strength)
  # Note: fuzzy set name can differ from indicator ID
  adx_trend:
    indicator: adx_14         # References the indicator ID
    weak:
      type: triangular
      parameters: [0, 15, 25]
    moderate:
      type: triangular
      parameters: [20, 35, 50]
    strong:
      type: triangular
      parameters: [45, 60, 100]

# ---------------------------------------------------------------------------
# NN INPUTS - Include both fuzzy sets
# ---------------------------------------------------------------------------
nn_inputs:
  - fuzzy_set: rsi_14
    timeframes: all
  - fuzzy_set: adx_trend
    timeframes: all

model:
  type: mlp
  architecture:
    hidden_layers: [64, 32]
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001

decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true

training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
