# =============================================================================
# V3 STRATEGY EXAMPLE: Single Indicator (Full Configuration)
# =============================================================================
# A complete single-indicator strategy showing all configuration options.
# Uses RSI with triangular membership functions.
#
# Use case: Production strategies with single indicator focus
# =============================================================================

name: v3_single_indicator_example
version: "3.0"
description: Single RSI indicator with full configuration options

# ---------------------------------------------------------------------------
# TRAINING DATA - What data to train on
# ---------------------------------------------------------------------------
training_data:
  symbols:
    mode: single              # Options: single, multi_symbol
    symbol: EURUSD            # For single mode, use 'symbol'
  timeframes:
    mode: single              # Options: single, multi_timeframe
    timeframe: "1h"           # For single mode, use 'timeframe'
  history_required: 200       # Bars of history needed for indicators

# ---------------------------------------------------------------------------
# INDICATORS - Technical indicators to compute (dict format in v3)
# ---------------------------------------------------------------------------
indicators:
  rsi_14:                     # Unique indicator ID (you choose the name)
    type: rsi                 # Indicator type (lowercase)
    period: 14
    source: close             # Price source: open, high, low, close

# ---------------------------------------------------------------------------
# FUZZY SETS - How to interpret indicator values
# ---------------------------------------------------------------------------
fuzzy_sets:
  rsi_14:                     # Fuzzy set name (often matches indicator ID)
    indicator: rsi_14         # Which indicator this interprets
    # Triangular membership functions: [left, peak, right]
    oversold:
      type: triangular
      parameters: [0, 30, 40]
    neutral:
      type: triangular
      parameters: [35, 50, 65]
    overbought:
      type: triangular
      parameters: [60, 70, 100]

# ---------------------------------------------------------------------------
# NN INPUTS - Which fuzzy outputs feed into the neural network
# ---------------------------------------------------------------------------
nn_inputs:
  - fuzzy_set: rsi_14
    timeframes: all           # Options: all, or list like ["1h", "4h"]

# ---------------------------------------------------------------------------
# MODEL - Neural network architecture
# ---------------------------------------------------------------------------
model:
  type: mlp
  architecture:
    hidden_layers: [64, 32]
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001

# ---------------------------------------------------------------------------
# DECISIONS - How to generate trading signals
# ---------------------------------------------------------------------------
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false

# ---------------------------------------------------------------------------
# TRAINING - Supervised learning configuration
# ---------------------------------------------------------------------------
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025   # 2.5% price swing
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
