name: volatility_breakout_v1_1734842466
description: A neuro-fuzzy strategy that identifies volatility breakout opportunities
  by combining ADX (trend strength), ATR (volatility measurement), and MACD (momentum
  confirmation). The strategy aims to catch high-probability moves when markets break
  out of low-volatility consolidation phases into trending moves. Trained on major
  forex pairs (EURUSD, GBPUSD, USDJPY) using 1-hour timeframes for universal deployment
  across all markets.
version: '3.0'
hypothesis: Markets alternate between low-volatility consolidation and high-volatility
  breakout phases. By identifying when volatility is compressed and trend strength
  is building, we can catch profitable breakout moves.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 200
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  adx_14:
    type: ADX
    period: 14
    source: close
  atr_20:
    type: ATR
    period: 20
    source: close
  macd_12:
    type: MACD
    period: 12
    source: close
fuzzy_sets:
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    building_trend:
      type: triangular
      parameters:
      - 20
      - 30
      - 40
    strong_trend:
      type: triangular
      parameters:
      - 35
      - 50
      - 100
    indicator: adx_14
  atr_20:
    low_volatility:
      type: triangular
      parameters:
      - 0
      - 0.3
      - 0.6
    normal_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.8
      - 1.2
    high_volatility:
      type: triangular
      parameters:
      - 1.0
      - 1.5
      - 3.0
    indicator: atr_20
  macd_12:
    bearish_momentum:
      type: triangular
      parameters:
      - -2.0
      - -0.5
      - 0
    neutral_momentum:
      type: triangular
      parameters:
      - -0.3
      - 0
      - 0.3
    bullish_momentum:
      type: triangular
      parameters:
      - 0
      - 0.5
      - 2.0
    indicator: macd_12
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 15
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: atr_20
  timeframes: all
- fuzzy_set: macd_12
  timeframes: all
