name: volatility_breakout_multi_v1
description: 'Innovative volatility breakout strategy that combines three complementary
  indicators: Bollinger Band Width (volatility compression), ADX (trend strength),
  and MACD (momentum direction). The hypothesis is that markets make significant moves
  after periods of low volatility, and by combining these indicators we can identify
  both the timing and direction of breakouts. Uses a deeper neural network (48-24-12)
  with higher confidence threshold (0.65) to focus on high-conviction signals.'
version: '3.0'
hypothesis: Markets make significant moves after low volatility periods. Combine volatility
  compression (BB Width), trend strength (ADX), and momentum direction (MACD) to catch
  breakouts.
scope: universal
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 300
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  bb_width_20:
    type: BollingerBandWidth
    period: 20
    source: close
  adx_14:
    type: ADX
    period: 14
    source: close
  macd_12:
    type: MACD
    period: 12
    source: close
fuzzy_sets:
  bb_width_20:
    compressed:
      type: triangular
      parameters:
      - 0
      - 0.005
      - 0.015
    normal:
      type: triangular
      parameters:
      - 0.01
      - 0.025
      - 0.04
    expanded:
      type: triangular
      parameters:
      - 0.035
      - 0.05
      - 0.1
    indicator: bb_width_20
  adx_14:
    weak:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    building:
      type: triangular
      parameters:
      - 30
      - 45
      - 60
    strong:
      type: triangular
      parameters:
      - 55
      - 70
      - 100
    indicator: adx_14
  macd_12:
    bearish:
      type: triangular
      parameters:
      - -0.01
      - -0.003
      - 0
    neutral:
      type: triangular
      parameters:
      - -0.002
      - 0
      - 0.002
    bullish:
      type: triangular
      parameters:
      - 0
      - 0.003
      - 0.01
    indicator: macd_12
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0008
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: bb_width_20
  timeframes: all
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: macd_12
  timeframes: all
