name: volatility_breakout_multidim_v1
description: Multi-dimensional volatility breakout strategy combining Fisher Transform
  momentum, dual volatility indicators (ATR/BBWidth), and volume confirmation (CMF)
version: '3.0'
hypothesis: Markets exhibit predictable behavior when volatility changes coincide
  with momentum shifts and volume confirmation. Fisher Transform provides momentum
  clarity, ATR/BBWidth measure volatility states, and CMF confirms with volume analysis.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  fisher_10:
    type: FisherTransform
    period: 10
    source: close
  atr_14:
    type: ATR
    period: 14
    source: close
  bbwidth_20:
    type: BollingerBandWidth
    period: 20
    source: close
  cmf_21:
    type: CMF
    period: 21
    source: close
fuzzy_sets:
  fisher_10:
    strong_bearish:
      type: triangular
      parameters:
      - -3.0
      - -2.0
      - -1.0
    bearish:
      type: triangular
      parameters:
      - -1.5
      - -0.5
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.3
      - 0.0
      - 0.3
    bullish:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    strong_bullish:
      type: triangular
      parameters:
      - 1.0
      - 2.0
      - 3.0
    indicator: fisher_10
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.002
      - 0.005
    medium_volatility:
      type: triangular
      parameters:
      - 0.003
      - 0.008
      - 0.015
    high_volatility:
      type: triangular
      parameters:
      - 0.01
      - 0.02
      - 0.05
    indicator: atr_14
  bbwidth_20:
    squeeze:
      type: triangular
      parameters:
      - 0.0
      - 0.01
      - 0.025
    normal:
      type: triangular
      parameters:
      - 0.02
      - 0.04
      - 0.07
    expansion:
      type: triangular
      parameters:
      - 0.06
      - 0.1
      - 0.2
    indicator: bbwidth_20
  cmf_21:
    strong_selling:
      type: triangular
      parameters:
      - -1.0
      - -0.3
      - -0.1
    neutral_flow:
      type: triangular
      parameters:
      - -0.15
      - 0.0
      - 0.15
    strong_buying:
      type: triangular
      parameters:
      - 0.1
      - 0.3
      - 1.0
    indicator: cmf_21
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.25
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 60
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0008
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: fisher_10
  timeframes: all
- fuzzy_set: atr_14
  timeframes: all
- fuzzy_set: bbwidth_20
  timeframes: all
- fuzzy_set: cmf_21
  timeframes: all
