name: volatility_breakout_multi_20241221
description: Innovative volatility breakout strategy that identifies low volatility
  compression periods followed by expansion with momentum confirmation. Uses Bollinger
  Band Width to detect compression, ATR for volatility confirmation, and MACD for
  directional momentum. Designed to capture high-probability breakout scenarios across
  multiple currency pairs.
version: '1.0'
hypothesis: Market breakouts occur when low volatility periods (compression) are followed
  by volatility expansion with momentum confirmation
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: BollingerBandWidth
  feature_id: bb_width_20
  period: 20
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
fuzzy_sets:
  bb_width_20:
    compressed:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.3
      - 0.5
    normal:
      type: triangular
      parameters:
      - 0.4
      - 0.7
      - 1.0
    expanding:
      type: trapezoidal
      parameters:
      - 0.8
      - 1.2
      - 2.0
      - 2.0
  atr_14:
    low:
      type: triangular
      parameters:
      - 0.0
      - 0.0
      - 0.4
    medium:
      type: triangular
      parameters:
      - 0.3
      - 0.5
      - 0.7
    high:
      type: triangular
      parameters:
      - 0.6
      - 1.0
      - 1.0
  macd_12:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -1.0
      - -1.0
      - -0.3
      - -0.1
    neutral:
      type: triangular
      parameters:
      - -0.2
      - 0.0
      - 0.2
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.1
      - 0.3
      - 1.0
      - 1.0
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
