name: volatility_breakout_1765518026
description: Volatility expansion breakout strategy combining trend strength, volatility
  context, and momentum confirmation
version: '1.0'
hypothesis: Markets make significant moves after volatility compression. Combining
  trend strength (ADX), volatility context (ATR), and momentum confirmation (MACD)
  identifies high-probability breakouts.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: ADX
  feature_id: adx_14
  period: 14
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
fuzzy_sets:
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate_trend:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong_trend:
      type: triangular
      parameters:
      - 40
      - 60
      - 100
  atr_14:
    low_volatility:
      type: gaussian
      parameters:
      - 0.0008
      - 0.0003
    normal_volatility:
      type: gaussian
      parameters:
      - 0.0015
      - 0.0005
    high_volatility:
      type: gaussian
      parameters:
      - 0.0025
      - 0.0008
  macd_12:
    bearish:
      type: sigmoid
      parameters:
      - -0.0005
      - 2000
    neutral:
      type: triangular
      parameters:
      - -0.0003
      - 0
      - 0.0003
    bullish:
      type: sigmoid
      parameters:
      - 0.0005
      - 2000
model:
  type: mlp
  architecture:
    hidden_layers:
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 40
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 8
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 15
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
