name: volatility_breakout_hunter_v1
description: Volatility breakout strategy combining Bollinger Band Width, ADX, and
  MACD to identify high-probability breakout opportunities after volatility compression
version: '3.0'
hypothesis: Markets experience significant moves after volatility compression. Fuzzy
  logic can identify optimal entry points by balancing volatility, trend strength,
  and momentum alignment.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  bb_width_20:
    type: BollingerBandWidth
    period: 20
    source: close
  adx_14:
    type: ADX
    period: 14
    source: close
  macd_12:
    type: MACD
    period: 12
    source: close
fuzzy_sets:
  bb_width_20:
    compressed:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.015
      - 0.025
    normal:
      type: triangular
      parameters:
      - 0.02
      - 0.035
      - 0.05
    expanded:
      type: trapezoidal
      parameters:
      - 0.045
      - 0.06
      - 1.0
      - 1.0
    indicator: bb_width_20
  adx_14:
    weak:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong:
      type: trapezoidal
      parameters:
      - 45
      - 60
      - 100
      - 100
    indicator: adx_14
  macd_12:
    bearish:
      type: trapezoidal
      parameters:
      - -1.0
      - -1.0
      - -0.002
      - -0.0005
    neutral:
      type: triangular
      parameters:
      - -0.001
      - 0.0
      - 0.001
    bullish:
      type: trapezoidal
      parameters:
      - 0.0005
      - 0.002
      - 1.0
      - 1.0
    indicator: macd_12
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    activation: relu
    output_activation: softmax
    dropout: 0.15
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 32
    epochs: 60
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0008
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: bb_width_20
  timeframes: all
- fuzzy_set: adx_14
  timeframes: all
- fuzzy_set: macd_12
  timeframes: all
