name: volatility_momentum_confluence_20241213
description: Captures breakouts using volatility expansion, momentum alignment, and
  volume flow confirmation
version: '3.0'
hypothesis: Markets make significant moves when volatility expands after compression,
  especially with momentum and money flow alignment
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  atr_14:
    type: ATR
    period: 14
    source: close
  macd_12:
    type: MACD
    period: 12
    source: close
  cmf_21:
    type: CMF
    period: 21
    source: close
  bb_width_20:
    type: BollingerBandWidth
    period: 20
    source: close
fuzzy_sets:
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.3
      - 0.6
    medium_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.7
      - 1.0
    high_volatility:
      type: triangular
      parameters:
      - 0.8
      - 1.2
      - 2.0
    indicator: atr_14
  macd_12:
    bearish_momentum:
      type: triangular
      parameters:
      - -0.05
      - -0.02
      - 0.0
    neutral_momentum:
      type: triangular
      parameters:
      - -0.01
      - 0.0
      - 0.01
    bullish_momentum:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    indicator: macd_12
  cmf_21:
    money_outflow:
      type: triangular
      parameters:
      - -0.3
      - -0.1
      - 0.0
    neutral_flow:
      type: triangular
      parameters:
      - -0.05
      - 0.0
      - 0.05
    money_inflow:
      type: triangular
      parameters:
      - 0.0
      - 0.1
      - 0.3
    indicator: cmf_21
  bb_width_20:
    compressed:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    normal:
      type: triangular
      parameters:
      - 0.03
      - 0.06
      - 0.1
    expanded:
      type: triangular
      parameters:
      - 0.08
      - 0.12
      - 0.2
    indicator: bb_width_20
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: atr_14
  timeframes: all
- fuzzy_set: macd_12
  timeframes: all
- fuzzy_set: cmf_21
  timeframes: all
- fuzzy_set: bb_width_20
  timeframes: all
