name: volatility_volume_breakout_v1
description: Volatility squeeze breakout detection with volume confirmation - targets
  breakouts following low volatility periods with volume expansion
version: '1.0'
hypothesis: Breakouts following volatility squeezes with volume expansion have higher
  success probability
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: BollingerBandWidth
  feature_id: bb_width_20
  period: 20
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: VolumeRatio
  feature_id: vol_ratio_10
  period: 10
  source: close
fuzzy_sets:
  bb_width_20:
    squeezed:
      type: triangular
      parameters:
      - 0.0
      - 0.3
      - 0.6
    normal:
      type: triangular
      parameters:
      - 0.4
      - 0.7
      - 1.0
    expanded:
      type: triangular
      parameters:
      - 0.8
      - 1.2
      - 2.0
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.25
      - 0.5
    medium_volatility:
      type: triangular
      parameters:
      - 0.3
      - 0.6
      - 0.9
    high_volatility:
      type: triangular
      parameters:
      - 0.7
      - 1.0
      - 1.5
  vol_ratio_10:
    low_volume:
      type: triangular
      parameters:
      - 0.0
      - 0.7
      - 1.0
    normal_volume:
      type: triangular
      parameters:
      - 0.8
      - 1.2
      - 1.6
    high_volume:
      type: triangular
      parameters:
      - 1.4
      - 2.0
      - 3.0
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.25
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
