name: volatility_volume_convergence_v1
description: Volatility-volume convergence strategy using Bollinger Band Width, MFI,
  and ATR for reversal detection
version: '1.0'
hypothesis: Market reversals occur when volatility contracts (low BBWidth) while smart
  money accumulates/distributes (MFI extremes), with ATR providing volatility confirmation
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: BollingerBandWidth
  feature_id: bb_width_20
  period: 20
  source: close
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
fuzzy_sets:
  bb_width_20:
    low_volatility:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.3
      - 0.6
    normal_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.8
      - 1.2
    high_volatility:
      type: trapezoidal
      parameters:
      - 1.0
      - 1.5
      - 3.0
      - 3.0
  mfi_14:
    oversold:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: trapezoidal
      parameters:
      - 65
      - 80
      - 100
      - 100
  atr_14:
    low_atr:
      type: gaussian
      parameters:
      - 0.0015
      - 0.0005
    medium_atr:
      type: gaussian
      parameters:
      - 0.004
      - 0.0015
    high_atr:
      type: gaussian
      parameters:
      - 0.008
      - 0.003
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 80
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
