name: volatility_breakout_v1
description: Multi-dimensional volatility breakout strategy combining squeeze detection,
  trend direction, volume flow, and momentum transformation
version: '3.0'
hypothesis: Markets alternate between low volatility consolidation and high volatility
  breakouts. By detecting squeeze conditions and confirming with trend, volume, and
  momentum, we can capture early breakout movements.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  bb_width_20:
    type: BollingerBandWidth
    period: 20
    source: close
  supertrend_14:
    type: SuperTrend
    period: 14
    source: close
  mfi_14:
    type: MFI
    period: 14
    source: close
  fisher_9:
    type: FisherTransform
    period: 9
    source: close
fuzzy_sets:
  bb_width_20:
    squeeze:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 0.15
      - 0.25
    normal:
      type: triangular
      parameters:
      - 0.2
      - 0.4
      - 0.6
    expansion:
      type: trapezoidal
      parameters:
      - 0.5
      - 0.7
      - 1.0
      - 1.0
    indicator: bb_width_20
  supertrend_14:
    bullish:
      type: sigmoid
      parameters:
      - 1
      - 10
    neutral:
      type: triangular
      parameters:
      - -0.1
      - 0
      - 0.1
    bearish:
      type: sigmoid
      parameters:
      - -1
      - -10
    indicator: supertrend_14
  mfi_14:
    oversold:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 35
    balanced:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: trapezoidal
      parameters:
      - 65
      - 80
      - 100
      - 100
    indicator: mfi_14
  fisher_9:
    strong_sell:
      type: trapezoidal
      parameters:
      - -5
      - -5
      - -2
      - -1
    neutral:
      type: triangular
      parameters:
      - -0.5
      - 0
      - 0.5
    strong_buy:
      type: trapezoidal
      parameters:
      - 1
      - 2
      - 5
      - 5
    indicator: fisher_9
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: bb_width_20
  timeframes: all
- fuzzy_set: supertrend_14
  timeframes: all
- fuzzy_set: mfi_14
  timeframes: all
- fuzzy_set: fisher_9
  timeframes: all
