name: volatility_squeeze_breakout_v1
description: Volatility breakout strategy combining Bollinger Band Width, ATR, and
  MACD to capture explosive moves after consolidation periods
version: '1.0'
hypothesis: Markets experience explosive moves when volatility expands after periods
  of consolidation. By combining volatility measures with momentum confirmation, we
  can identify high-probability breakout opportunities.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: BollingerBandWidth
  feature_id: bbwidth_20
  period: 20
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
fuzzy_sets:
  bbwidth_20:
    very_low:
      type: triangular
      parameters:
      - 0.0
      - 0.001
      - 0.003
    low:
      type: triangular
      parameters:
      - 0.002
      - 0.005
      - 0.008
    normal:
      type: triangular
      parameters:
      - 0.006
      - 0.012
      - 0.02
    high:
      type: triangular
      parameters:
      - 0.015
      - 0.025
      - 0.04
    very_high:
      type: triangular
      parameters:
      - 0.03
      - 0.05
      - 0.1
  atr_14:
    very_low:
      type: triangular
      parameters:
      - 0.0
      - 0.002
      - 0.004
    low:
      type: triangular
      parameters:
      - 0.003
      - 0.006
      - 0.01
    moderate:
      type: triangular
      parameters:
      - 0.008
      - 0.014
      - 0.02
    high:
      type: triangular
      parameters:
      - 0.015
      - 0.025
      - 0.04
    very_high:
      type: triangular
      parameters:
      - 0.03
      - 0.05
      - 0.1
  macd_12:
    strongly_negative:
      type: triangular
      parameters:
      - -0.01
      - -0.005
      - -0.001
    negative:
      type: triangular
      parameters:
      - -0.003
      - -0.001
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.001
      - 0.0
      - 0.001
    positive:
      type: triangular
      parameters:
      - 0.0
      - 0.001
      - 0.003
    strongly_positive:
      type: triangular
      parameters:
      - 0.001
      - 0.005
      - 0.01
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
