name: volatility_momentum_confluence_20241224
description: Innovative strategy combining volatility patterns (ATR), normalized momentum
  (Fisher Transform), and trend strength (Aroon) to identify high-probability trading
  opportunities
version: '1.0'
hypothesis: High-probability trading opportunities occur when volatility indicators
  signal upcoming breakouts while momentum indicators confirm directional bias and
  trend strength validates the move
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: FisherTransform
  feature_id: fisher_10
  period: 10
  source: close
- name: Aroon
  feature_id: aroon_25
  period: 25
  source: close
fuzzy_sets:
  atr_14:
    low_volatility:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.3
      - 0.5
    normal_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.6
      - 0.8
    high_volatility:
      type: trapezoidal
      parameters:
      - 0.7
      - 0.9
      - 1.0
      - 1.0
  fisher_10:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -3.0
      - -3.0
      - -1.5
      - -0.8
    neutral:
      type: triangular
      parameters:
      - -0.5
      - 0.0
      - 0.5
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.8
      - 1.5
      - 3.0
      - 3.0
  aroon_25:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 25
      - 50
    moderate_trend:
      type: triangular
      parameters:
      - 40
      - 60
      - 80
    strong_trend:
      type: trapezoidal
      parameters:
      - 70
      - 85
      - 100
      - 100
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0008
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
