name: volatility_breakout_momentum_v1
description: Multi-dimensional volatility breakout strategy using Bollinger Band Width,
  Fisher Transform, and ADX
version: '1.0'
hypothesis: Market volatility contraction followed by momentum expansion with trend
  strength confirmation creates predictable price movements
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - AUDUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: BollingerBandWidth
  feature_id: bb_width_20
  period: 20
  source: close
- name: FisherTransform
  feature_id: fisher_10
  period: 10
  source: close
- name: ADX
  feature_id: adx_14
  period: 14
  source: close
fuzzy_sets:
  bb_width_20:
    low_volatility:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.02
      - 0.04
    moderate_volatility:
      type: triangular
      parameters:
      - 0.03
      - 0.06
      - 0.09
    high_volatility:
      type: trapezoidal
      parameters:
      - 0.08
      - 0.12
      - 1.0
      - 1.0
  fisher_10:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -5.0
      - -5.0
      - -1.5
      - -0.5
    neutral:
      type: triangular
      parameters:
      - -1.0
      - 0.0
      - 1.0
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.5
      - 1.5
      - 5.0
      - 5.0
  adx_14:
    weak_trend:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 30
    moderate_trend:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    strong_trend:
      type: trapezoidal
      parameters:
      - 50
      - 65
      - 100
      - 100
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    activation: relu
    output_activation: softmax
    dropout: 0.25
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
