name: volatility_breakout_fisher_v1
description: Multi-dimensional volatility breakout strategy using ATR, Squeeze Intensity,
  and Fisher Transform
version: '1.0'
hypothesis: Markets experience explosive directional moves after volatility compression
  periods. Combining volatility measurement, squeeze detection, and precise turning
  point identification can capture high-probability breakout opportunities.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: SqueezeIntensity
  feature_id: squeeze_intensity_20
  period: 20
  source: close
- name: FisherTransform
  feature_id: fisher_transform_10
  period: 10
  source: close
fuzzy_sets:
  atr_14:
    low_volatility:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.3
      - 0.5
    normal_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.7
      - 1.0
    high_volatility:
      type: trapezoidal
      parameters:
      - 0.8
      - 1.2
      - 2.0
      - 2.0
  squeeze_intensity_20:
    tight_squeeze:
      type: trapezoidal
      parameters:
      - 0.0
      - 0.0
      - 0.2
      - 0.4
    moderate_squeeze:
      type: triangular
      parameters:
      - 0.3
      - 0.5
      - 0.7
    no_squeeze:
      type: trapezoidal
      parameters:
      - 0.6
      - 0.8
      - 1.0
      - 1.0
  fisher_transform_10:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -3.0
      - -3.0
      - -1.5
      - -0.8
    neutral:
      type: triangular
      parameters:
      - -0.5
      - 0.0
      - 0.5
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.8
      - 1.5
      - 3.0
      - 3.0
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 60
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
