name: volatility_breakout_regime_v1
description: Multi-dimensional volatility breakout strategy identifying regime changes
  through ATR, Bollinger Band Width, MACD momentum, MFI volume flow, and ADX trend
  strength
version: '1.0'
hypothesis: Markets alternate between low-volatility consolidation and high-volatility
  breakout periods. By identifying volatility expansion combined with momentum, volume
  flow, and trend strength confirmation, we can capture significant directional moves.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: BollingerBandWidth
  feature_id: bb_width_20
  period: 20
  source: close
- name: MACD
  feature_id: macd_12_26
  period: 12
  source: close
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: ADX
  feature_id: adx_14
  period: 14
  source: close
fuzzy_sets:
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0.0
      - 0.3
      - 0.6
    medium_volatility:
      type: triangular
      parameters:
      - 0.4
      - 0.7
      - 1.0
    high_volatility:
      type: triangular
      parameters:
      - 0.8
      - 1.2
      - 2.0
  bb_width_20:
    squeezed:
      type: triangular
      parameters:
      - 0.0
      - 0.02
      - 0.05
    normal:
      type: triangular
      parameters:
      - 0.03
      - 0.06
      - 0.1
    expanding:
      type: triangular
      parameters:
      - 0.08
      - 0.15
      - 0.3
  macd_12_26:
    bearish:
      type: triangular
      parameters:
      - -0.01
      - -0.005
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.002
      - 0.0
      - 0.002
    bullish:
      type: triangular
      parameters:
      - 0.0
      - 0.005
      - 0.01
  mfi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    balanced:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate_trend:
      type: triangular
      parameters:
      - 20
      - 30
      - 40
    strong_trend:
      type: triangular
      parameters:
      - 35
      - 50
      - 100
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
