name: volume_momentum_divergence_v1
description: Mean reversion strategy based on volume-momentum divergence patterns
version: '3.0'
hypothesis: When momentum extremes occur with weak volume conviction, mean reversion
  is likely
scope: universal
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 150
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
  macd_12:
    type: MACD
    period: 12
    source: close
  mfi_14:
    type: MFI
    period: 14
    source: close
  roc_10:
    type: ROC
    period: 10
    source: close
fuzzy_sets:
  macd_12:
    strong_bearish:
      type: triangular
      parameters:
      - -0.02
      - -0.01
      - -0.003
    weak_bearish:
      type: triangular
      parameters:
      - -0.005
      - -0.001
      - 0.0
    neutral:
      type: triangular
      parameters:
      - -0.002
      - 0.0
      - 0.002
    weak_bullish:
      type: triangular
      parameters:
      - 0.0
      - 0.001
      - 0.005
    strong_bullish:
      type: triangular
      parameters:
      - 0.003
      - 0.01
      - 0.02
    indicator: macd_12
  mfi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    weak:
      type: triangular
      parameters:
      - 25
      - 40
      - 55
    neutral:
      type: triangular
      parameters:
      - 45
      - 50
      - 55
    strong:
      type: triangular
      parameters:
      - 45
      - 60
      - 75
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: mfi_14
  roc_10:
    strong_decline:
      type: triangular
      parameters:
      - -5.0
      - -2.0
      - -0.5
    mild_decline:
      type: triangular
      parameters:
      - -1.5
      - -0.5
      - 0.0
    sideways:
      type: triangular
      parameters:
      - -0.5
      - 0.0
      - 0.5
    mild_advance:
      type: triangular
      parameters:
      - 0.0
      - 0.5
      - 1.5
    strong_advance:
      type: triangular
      parameters:
      - 0.5
      - 2.0
      - 5.0
    indicator: roc_10
model:
  type: mlp
  architecture:
    hidden_layers:
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 40
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 8
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 15
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: macd_12
  timeframes: all
- fuzzy_set: mfi_14
  timeframes: all
- fuzzy_set: roc_10
  timeframes: all
