name: volume_surge_momentum
description: Volume surge strategy capturing explosive moves with institutional activity
version: '3.0'
hypothesis: Volume surge patterns combined with price breakouts indicate institutional
  accumulation and create high-probability directional moves
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - TSLA
    - NVDA
    - BTCUSD
    - SOLUSDT
  timeframes:
    mode: multi_timeframe
    list:
    - 5m
    - 15m
    - 1h
    base_timeframe: 5m
  history_required: 200
deployment:
  target_symbols:
    mode: group_restricted
  target_timeframes:
    mode: multi_timeframe
    supported:
    - 5m
    - 15m
    - 1h
indicators:
  rsi_14:
    type: rsi
    period: 14
    source: close
  macd_12_26_9:
    type: macd
    fast_period: 12
    slow_period: 26
    signal_period: 9
    source: close
fuzzy_sets:
  rsi_14:
    oversold:
      type: triangular
      parameters:
      - 0
      - 20
      - 35
    neutral:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    overbought:
      type: triangular
      parameters:
      - 65
      - 80
      - 100
    indicator: rsi_14
model:
  type: mlp
  architecture:
    hidden_layers:
    - 50
    - 25
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 2
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    optimizer: adam
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
  filters:
    min_signal_separation: 4
    volume_filter: false
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
nn_inputs:
- fuzzy_set: rsi_14
  timeframes: all
