name: volume_momentum_breakout_20251211
description: Volume-backed momentum breakout strategy using MFI, CMF, MACD, and ATR
version: '1.0'
hypothesis: Strong price moves backed by significant volume and momentum indicate
  institutional participation with high continuation probability
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: CMF
  feature_id: cmf_20
  period: 20
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
fuzzy_sets:
  mfi_14:
    low_volume:
      type: triangular
      parameters:
      - 0
      - 20
      - 40
    normal_volume:
      type: triangular
      parameters:
      - 30
      - 50
      - 70
    high_volume:
      type: triangular
      parameters:
      - 60
      - 80
      - 100
  cmf_20:
    accumulation:
      type: triangular
      parameters:
      - 0.1
      - 0.3
      - 0.5
    neutral_flow:
      type: triangular
      parameters:
      - -0.2
      - 0
      - 0.2
    distribution:
      type: triangular
      parameters:
      - -0.5
      - -0.3
      - -0.1
  macd_12:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -0.01
      - -0.005
      - -0.003
      - -0.001
    weak_momentum:
      type: triangular
      parameters:
      - -0.002
      - 0
      - 0.002
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.001
      - 0.003
      - 0.005
      - 0.01
  atr_14:
    low_volatility:
      type: triangular
      parameters:
      - 0
      - 0.0005
      - 0.002
    medium_volatility:
      type: triangular
      parameters:
      - 0.001
      - 0.003
      - 0.005
    high_volatility:
      type: triangular
      parameters:
      - 0.004
      - 0.007
      - 0.015
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 80
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
