name: volume_volatility_breakout_v1
description: Volume-volatility confluence strategy targeting breakout opportunities
  after compression periods
version: '1.0'
hypothesis: Major price movements are preceded by unusual volume activity combined
  with volatility compression patterns
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: MFI
  feature_id: mfi_21
  period: 21
  source: close
- name: VWAP
  feature_id: vwap_20
  period: 20
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
- name: ROC
  feature_id: roc_10
  period: 10
  source: close
fuzzy_sets:
  mfi_21:
    low_flow:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 35
    neutral_flow:
      type: trapezoidal
      parameters:
      - 25
      - 40
      - 60
      - 75
    high_flow:
      type: trapezoidal
      parameters:
      - 65
      - 80
      - 100
      - 100
  vwap_20:
    below_vwap:
      type: sigmoid
      parameters:
      - -0.001
      - 1000
    near_vwap:
      type: gaussian
      parameters:
      - 0
      - 0.002
    above_vwap:
      type: sigmoid
      parameters:
      - 0.001
      - 1000
  atr_14:
    low_volatility:
      type: gaussian
      parameters:
      - 0.0005
      - 0.0003
    normal_volatility:
      type: gaussian
      parameters:
      - 0.0015
      - 0.0005
    high_volatility:
      type: gaussian
      parameters:
      - 0.003
      - 0.001
  roc_10:
    negative_momentum:
      type: triangular
      parameters:
      - -5
      - -2
      - 0
    neutral_momentum:
      type: triangular
      parameters:
      - -1
      - 0
      - 1
    positive_momentum:
      type: triangular
      parameters:
      - 0
      - 2
      - 5
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 75
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 12
      min_delta: 0.0008
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
