# High Risk/Reward Aggressive Strategy
name: "volume_surge_momentum"
description: "Captures explosive moves on 300%+ volume with Donchian breakouts"
version: "1.0"

# Data requirements
data:
  symbols: ["TSLA", "NVDA", "BTCUSD", "SOLUSDT"]
  timeframes: ["5m", "15m", "1h"]  # Multi-timeframe
  history_required: 100

# Technical indicators configuration
indicators:
  - name: donchian_channel
    period: 20
  - name: volume_sma
    period: 50
  - name: rsi
    period: 7      # Fast RSI for momentum
  - name: atr
    period: 14
  - name: ema
    period: 9      # Fast EMA
  - name: vwap
    period: 1      # Daily VWAP

# Fuzzy logic configuration
fuzzy_sets:
  volume_surge:
    normal:
      type: triangular
      parameters: [0, 1.0, 2.0]
    elevated:
      type: triangular
      parameters: [1.5, 2.0, 3.0]
    high:
      type: triangular
      parameters: [2.5, 3.0, 4.0]
    extreme:
      type: triangular
      parameters: [3.5, 5.0, 8.0]
  
  price_position:
    near_low:
      type: triangular
      parameters: [0, 0.1, 0.3]
    mid_range:
      type: triangular
      parameters: [0.2, 0.5, 0.8]
    near_high:
      type: triangular
      parameters: [0.7, 0.9, 1.0]
    breakout:
      type: triangular
      parameters: [0.95, 1.0, 1.05]
  
  momentum_strength:
    weak:
      type: triangular
      parameters: [0, 30, 50]
    moderate:
      type: triangular
      parameters: [40, 60, 80]
    strong:
      type: triangular
      parameters: [70, 85, 100]

# Neural network configuration
model:
  type: "cnn_lstm"  # Hybrid for pattern + sequence
  architecture:
    cnn_filters: [32, 64]
    cnn_kernel_size: 3
    lstm_units: [50, 25]
    dense_layers: [20, 10]
    activation: "relu"
    output_activation: "softmax"
    dropout: 0.3
  
  training:
    learning_rate: 0.002
    batch_size: 16
    epochs: 150
    optimizer: "adamw"
    weight_decay: 0.001
    
    lr_scheduler:
      type: "exponential"
      gamma: 0.95
    
    early_stopping:
      patience: 20
      monitor: "val_loss"
      min_delta: 0.0001
  
  features:
    include_price_context: true
    include_volume_context: true
    include_microstructure: true  # Bid-ask, order flow
    lookback_periods: 10         # Capture surge buildup
    scale_features: true
    scaling_method: "robust"     # Handle outliers

# Decision logic configuration
decisions:
  output_format: "classification"
  confidence_threshold: 0.55     # Lower for aggressive
  position_awareness: true
  
  filters:
    min_signal_separation: 2     # Quick re-entry allowed
    volume_filter: true
    min_volume_surge: 3.0       # 300% minimum

# Aggressive strategy rules
orchestrator:
  max_position_size: 0.80       # Smaller for risk management
  signal_cooldown: 2
  
  # Multi-timeframe confirmation
  timeframe_alignment:
    primary: "5m"               # Entry timeframe
    confirmation: "1h"          # Trend confirmation
    
  entry_rules:
    long:
      - volume_surge_extreme: "> 0.8"
      - price_position_breakout: "> 0.7"
      - momentum_strength_strong: "> 0.6"
      - higher_tf_trend: "bullish"
    short:
      - volume_surge_extreme: "> 0.8"
      - price_position_near_low: "> 0.7"
      - momentum_strength_strong: "> 0.6"
      - higher_tf_trend: "bearish"
  
  # Quick exits for momentum
  exit_rules:
    time_based:
      max_bars: 20              # Exit within 20 bars
    momentum_based:
      rsi_exhaustion: 85        # Exit on RSI extremes
    trailing_stop:
      activation: 2.0           # Activate at 2R profit
      distance: 1.0             # Trail by 1 ATR
  
  modes:
    backtest:
      confidence_threshold: 0.50
    paper:
      confidence_threshold: 0.55
    live:
      confidence_threshold: 0.60
      max_daily_trades: 5       # Risk control

# Training configuration
training:
  method: "supervised"
  labels:
    source: "zigzag"
    zigzag_threshold: 0.05      # 5% for explosive moves
    label_lookahead: 20         # Quick momentum trades
  
  # Imbalanced dataset handling
  class_weights:
    buy: 1.0
    hold: 0.5                   # Reduce hold weight
    sell: 1.0
  
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
  
  fitness_metrics:
    primary: "profit_factor"
    secondary: ["risk_reward_ratio", "sharpe_ratio"]

# Aggressive risk management
risk_management:
  position_sizing: "kelly_criterion"
  kelly_fraction: 0.25          # Conservative Kelly
  min_position_size: 0.005      # 0.5% minimum
  max_position_size: 0.03       # 3% maximum
  max_portfolio_risk: 0.15      # 15% aggressive limit
  
  stop_loss:
    type: "swing_based"
    lookback: 5                 # Recent swing low/high
    atr_buffer: 0.3            # Tight stop
  
  take_profit:
    type: "multiple_targets"
    targets: [2.0, 3.5, 5.0]   # Scale out at 2R, 3.5R, 5R
    percentages: [0.4, 0.4, 0.2]

# Backtesting configuration
backtesting:
  start_date: "2021-01-01"
  end_date: "2024-01-01"
  initial_capital: 50000        # Smaller for aggressive
  transaction_costs: 0.002      # Higher for frequent trading
  slippage: 0.001              # Higher for momentum
