name: volume_momentum_divergence_1765518926
description: 'Volume-Momentum Divergence Strategy: Captures market turning points
  by identifying divergences between price momentum (MACD) and institutional money
  flow (MFI), with volatility context (ATR) for robust signal generation. Targets
  4-hour timeframe across major currency pairs to leverage institutional trading patterns.'
version: '1.0'
hypothesis: Market turning points exhibit divergences between price momentum and volume
  flow, creating profitable trading opportunities when institutional money contradicts
  short-term price action
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - AUDUSD
  timeframes:
    mode: single
    list:
    - 4h
    base_timeframe: 4h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 4h
indicators:
- name: MACD
  feature_id: macd_12_26
  period: 12
  source: close
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: ATR
  feature_id: atr_14
  period: 14
  source: close
fuzzy_sets:
  macd_12_26:
    strong_bearish:
      type: trapezoidal
      parameters:
      - -2.0
      - -1.0
      - -0.5
      - -0.2
    bearish:
      type: triangular
      parameters:
      - -0.5
      - -0.1
      - 0.1
    neutral:
      type: triangular
      parameters:
      - -0.1
      - 0.0
      - 0.1
    bullish:
      type: triangular
      parameters:
      - -0.1
      - 0.1
      - 0.5
    strong_bullish:
      type: trapezoidal
      parameters:
      - 0.2
      - 0.5
      - 1.0
      - 2.0
  mfi_14:
    oversold:
      type: trapezoidal
      parameters:
      - 0
      - 10
      - 20
      - 30
    low:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    neutral:
      type: triangular
      parameters:
      - 40
      - 50
      - 60
    high:
      type: triangular
      parameters:
      - 50
      - 65
      - 80
    overbought:
      type: trapezoidal
      parameters:
      - 70
      - 80
      - 90
      - 100
  atr_14:
    low_volatility:
      type: gaussian
      parameters:
      - 0.001
      - 0.0005
    medium_volatility:
      type: gaussian
      parameters:
      - 0.003
      - 0.001
    high_volatility:
      type: gaussian
      parameters:
      - 0.006
      - 0.002
model:
  type: mlp
  architecture:
    hidden_layers:
    - 64
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.3
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 24
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
