name: volume_momentum_breakout_v1
description: Volume-momentum breakout strategy using MFI, ROC, and ATR to capture
  strong directional moves
version: '1.0'
hypothesis: Strong price movements backed by significant volume flows and momentum
  tend to continue in the same direction
scope: universal
training_data:
  symbols:
    mode: single
    list:
    - EURUSD
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: training_only
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: ROC
  feature_id: roc_10
  period: 10
  source: close
- name: ATR
  feature_id: atr_20
  period: 20
  source: close
fuzzy_sets:
  mfi_14:
    oversold:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 30
    neutral:
      type: triangular
      parameters:
      - 25
      - 50
      - 75
    overbought:
      type: trapezoidal
      parameters:
      - 70
      - 80
      - 100
      - 100
  roc_10:
    negative:
      type: trapezoidal
      parameters:
      - -10
      - -10
      - -1
      - 0
    neutral:
      type: triangular
      parameters:
      - -0.5
      - 0
      - 0.5
    positive:
      type: trapezoidal
      parameters:
      - 0
      - 1
      - 10
      - 10
  atr_20:
    low_volatility:
      type: gaussian
      parameters:
      - 0.0005
      - 0.0002
    normal_volatility:
      type: gaussian
      parameters:
      - 0.0015
      - 0.0005
    high_volatility:
      type: gaussian
      parameters:
      - 0.003
      - 0.001
model:
  type: mlp
  architecture:
    hidden_layers:
    - 32
    - 16
    activation: relu
    output_activation: softmax
    dropout: 0.2
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 50
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 10
      min_delta: 0.001
decisions:
  output_format: classification
  confidence_threshold: 0.6
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.03
    label_lookahead: 20
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
