name: volume_momentum_confluence_v1
description: Multi-dimensional strategy combining volume-weighted momentum (MFI),
  trend strength (ADX), and momentum oscillation (MACD) for high-confidence trading
  signals
version: '1.0'
hypothesis: Market moves are more reliable when volume confirms momentum. Strong momentum
  signals backed by significant volume activity indicate higher probability trades.
scope: universal
training_data:
  symbols:
    mode: multi_symbol
    list:
    - EURUSD
    - GBPUSD
    - USDJPY
  timeframes:
    mode: single
    list:
    - 1h
    base_timeframe: 1h
  history_required: 250
deployment:
  target_symbols:
    mode: universal
  target_timeframes:
    mode: single
    supported:
    - 1h
indicators:
- name: MFI
  feature_id: mfi_14
  period: 14
  source: close
- name: ADX
  feature_id: adx_14
  period: 14
  source: close
- name: MACD
  feature_id: macd_12
  period: 12
  source: close
fuzzy_sets:
  mfi_14:
    oversold:
      type: trapezoidal
      parameters:
      - 0
      - 0
      - 20
      - 30
    neutral:
      type: trapezoidal
      parameters:
      - 25
      - 40
      - 60
      - 75
    overbought:
      type: trapezoidal
      parameters:
      - 70
      - 80
      - 100
      - 100
  adx_14:
    weak_trend:
      type: triangular
      parameters:
      - 0
      - 15
      - 25
    moderate_trend:
      type: triangular
      parameters:
      - 20
      - 35
      - 50
    strong_trend:
      type: triangular
      parameters:
      - 40
      - 65
      - 100
  macd_12:
    bearish:
      type: sigmoid
      parameters:
      - -0.5
      - 10
    neutral:
      type: gaussian
      parameters:
      - 0
      - 0.3
    bullish:
      type: sigmoid
      parameters:
      - 0.5
      - 10
model:
  type: mlp
  architecture:
    hidden_layers:
    - 48
    - 24
    - 12
    activation: relu
    output_activation: softmax
    dropout: 0.25
  features:
    include_price_context: false
    lookback_periods: 3
    scale_features: true
  training:
    learning_rate: 0.0008
    batch_size: 64
    epochs: 100
    optimizer: adam
    early_stopping:
      enabled: true
      patience: 15
      min_delta: 0.0005
decisions:
  output_format: classification
  confidence_threshold: 0.65
  position_awareness: true
training:
  method: supervised
  labels:
    source: zigzag
    zigzag_threshold: 0.025
    label_lookahead: 25
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
