services:
  # FastAPI backend service - Development configuration
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ktrdr-backend:dev
    container_name: ktrdr-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot-reloading
      - ./ktrdr:/app/ktrdr
      # Mount tests directory for running tests
      - ./tests:/app/tests
      # Mount data and logs directories for persistence
      - ./data:/app/data
      - ./logs:/app/logs
      # Mount config as read-only
      - ./config:/app/config:ro
      # Mount output directory for visualization files
      - ./output:/app/output
      # Cache directories for pip and uv
      - pip-cache:/root/.cache/pip
      - uv-cache:/root/.cache/uv
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ktrdr-network

networks:
  ktrdr-network:
    driver: bridge

volumes:
  pip-cache:
  uv-cache: