# Production environment configuration
# Overrides values from the central metadata file

api:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 8000
  reload: false
  log_level: "INFO"

logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s [%(process)d]: %(message)s"