# Documentation configuration for KTRDR API

# Organization Information
organization:
  name: "KTRDR"
  website: "https://ktrdr.mynerd.place"
  github: "https://github.com/kpiteira/ktrdr"
  email: "karl@mynerd.place"
  docs_url: "https://ktrdr-docs.mynerd.place"

# API Information
api:
  title: "KTRDR API"
  description: "REST API for KTRDR trading system"
  version: "1.0.5"
  base_url: "http://127.0.0.1:8000"
  prefix: "/api/v1"

# Branding
branding:
  logo_url: "https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png"
  logo_alt: "KTRDR API Logo"
  primary_color: "#4CAF50"
  secondary_color: "#1a1a1a"

# Examples
examples:
  symbols: ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]
  timeframes: ["1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1w", "1M"]
  default_symbol: "AAPL"
  default_timeframe: "1d"