# KTRDR Central Metadata - Single source of truth for project configuration
# This file serves as the authoritative source for all project metadata

# Project Identification
project:
  name: "KTRDR"
  full_name: "KTRDR Trading System"
  description: "Advanced trading system with fuzzy logic and machine learning capabilities"
  version: "1.0.6.1"  # Matches current version in pyproject.toml
  license: "Proprietary"
  
# Organization Information
organization:
  name: "KTRDR"
  website: "https://ktrdr.mynerd.place"
  github: "https://github.com/kpiteira/ktrdr"
  email: "karl@mynerd.place"
  docs_url: "https://ktrdr-docs.mynerd.place"
  
# API Configuration
api:
  title: "KTRDR API"
  description: "REST API for KTRDR trading system"
  prefix: "/api/v1"
  cors_origins: ["*"]
  default_version: "v1"
  
# Docker Configuration
docker:
  labels:
    title: "KTRDR Backend"
    description: "KTRDR trading system backend API"
    licenses: "Proprietary"
    authors: "KTRDR Team"
    documentation: "https://ktrdr-docs.mynerd.place"
  
# UI Configuration  
ui:
  title: "KTRDR Dashboard"
  theme:
    primary_color: "#4CAF50"
    secondary_color: "#1a1a1a"
  logo_url: "https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png"
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  
# Examples for Documentation
examples:
  symbols: ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]
  timeframes: ["1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1w", "1M"]
  default_symbol: "AAPL"
  default_timeframe: "1d"