# Multi-Timeframe Neural Network Training Configuration
# This configuration defines complete settings for training multi-timeframe neural networks

# Training Data Specification
data_spec:
  symbol: "AAPL"
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  timeframes: ["1h", "4h", "1d"]
  lookback_periods:
    "1h": 500    # Minimum 500 hours of data
    "4h": 200    # Minimum 200 4-hour periods  
    "1d": 100    # Minimum 100 days of data

# Data Preparation Configuration
data_preparation:
  sequence_length: 100           # Number of time steps in each training sequence
  prediction_horizon: 5          # Steps ahead to predict (5 periods)
  overlap_ratio: 0.3            # 30% overlap between sequences
  min_data_quality: 0.85        # Minimum data quality threshold (85%)
  
  # Timeframe weights for feature importance
  timeframe_weights:
    "1h": 1.0                   # Full weight for 1-hour data
    "4h": 0.8                   # 80% weight for 4-hour data
    "1d": 0.6                   # 60% weight for daily data
  
  # Data cleaning parameters
  cleaning:
    outlier_threshold: 3.0       # Standard deviations for outlier detection
    missing_data_max_ratio: 0.1  # Maximum 10% missing data per column
    temporal_gap_max_ratio: 0.05 # Maximum 5% temporal gaps

# Multi-Timeframe Indicator Configuration
indicator_config:
  timeframes:
    - timeframe: "1h"
      indicators:
        - type: "RSI"
          params:
            period: 14
            source: "close"
        - type: "SimpleMovingAverage"
          params:
            period: 20
            source: "close"
        - type: "ExponentialMovingAverage"
          params:
            period: 12
            source: "close"
        - type: "MACD"
          params:
            fast_period: 12
            slow_period: 26
            signal_period: 9
            source: "close"
        - type: "BollingerBands"
          params:
            period: 20
            std_dev: 2.0
            source: "close"
      enabled: true
      weight: 1.0

    - timeframe: "4h"
      indicators:
        - type: "RSI"
          params:
            period: 14
            source: "close"
        - type: "SimpleMovingAverage"
          params:
            period: 50
            source: "close"
        - type: "ExponentialMovingAverage"
          params:
            period: 21
            source: "close"
        - type: "ATR"
          params:
            period: 14
      enabled: true
      weight: 0.8

    - timeframe: "1d"
      indicators:
        - type: "RSI"
          params:
            period: 14
            source: "close"
        - type: "SimpleMovingAverage"
          params:
            period: 200
            source: "close"
        - type: "ExponentialMovingAverage"
          params:
            period: 50
            source: "close"
      enabled: true
      weight: 0.6

# Fuzzy Logic Configuration
fuzzy_config:
  # Fuzzy variables definition
  variables:
    rsi:
      type: "indicator"
      membership_functions:
        oversold:
          type: "trapezoidal"
          points: [0, 0, 25, 35]
        neutral:
          type: "triangular"
          points: [25, 50, 75]
        overbought:
          type: "trapezoidal"
          points: [65, 75, 100, 100]
    
    price_trend:
      type: "price_action"
      membership_functions:
        bearish:
          type: "trapezoidal"
          points: [-1.0, -1.0, -0.3, -0.1]
        neutral:
          type: "triangular"
          points: [-0.2, 0.0, 0.2]
        bullish:
          type: "trapezoidal"
          points: [0.1, 0.3, 1.0, 1.0]
    
    volume_surge:
      type: "volume"
      membership_functions:
        low:
          type: "trapezoidal"
          points: [0, 0, 0.8, 1.2]
        normal:
          type: "triangular"
          points: [0.8, 1.0, 1.5]
        high:
          type: "trapezoidal"
          points: [1.2, 1.8, 3.0, 3.0]

  # Fuzzy rules for multi-timeframe analysis
  rules:
    strong_buy_signal:
      conditions:
        - variable: "rsi"
          term: "oversold"
          timeframes: ["1h", "4h"]
          weight: 0.8
        - variable: "price_trend"
          term: "bullish"
          timeframes: ["4h", "1d"]
          weight: 1.0
      output:
        signal: "buy"
        confidence: 0.9
    
    strong_sell_signal:
      conditions:
        - variable: "rsi"
          term: "overbought"
          timeframes: ["1h", "4h"]
          weight: 0.8
        - variable: "price_trend"
          term: "bearish"
          timeframes: ["4h", "1d"]
          weight: 1.0
      output:
        signal: "sell"
        confidence: 0.9
    
    consolidation_signal:
      conditions:
        - variable: "rsi"
          term: "neutral"
          timeframes: ["1h", "4h", "1d"]
          weight: 0.6
        - variable: "price_trend"
          term: "neutral"
          timeframes: ["4h", "1d"]
          weight: 0.8
      output:
        signal: "hold"
        confidence: 0.7

# Neural Network Configuration
neural_config:
  # Timeframe-specific feature configuration
  timeframe_configs:
    "1h":
      expected_features:
        - "rsi_membership"
        - "trend_membership"
        - "volume_membership"
        - "momentum_strength"
        - "volatility_regime"
      weight: 1.0
      enabled: true
    
    "4h":
      expected_features:
        - "rsi_membership"
        - "trend_membership"
        - "momentum_strength"
        - "trend_alignment"
      weight: 0.8
      enabled: true
    
    "1d":
      expected_features:
        - "rsi_membership"
        - "trend_membership"
        - "long_term_momentum"
      weight: 0.6
      enabled: true

  # Neural network architecture
  architecture:
    hidden_layers: [128, 64, 32, 16]  # Deep network for complex patterns
    dropout: 0.4                      # Higher dropout for regularization
    activation: "relu"                # ReLU activation
    batch_norm: true                  # Batch normalization
    output_activation: "softmax"      # Softmax for classification
    
  # Training hyperparameters
  training:
    learning_rate: 0.0005            # Lower learning rate for stability
    batch_size: 64                   # Larger batch size
    epochs: 200                      # More epochs for convergence
    early_stopping_patience: 25     # Patience for early stopping
    optimizer: "adamw"               # AdamW optimizer with weight decay
    weight_decay: 0.01               # L2 regularization
    
    # Learning rate scheduling
    lr_scheduler:
      type: "reduce_on_plateau"
      factor: 0.5
      patience: 10
      min_lr: 0.00001
    
    # Gradient clipping
    gradient_clip: 1.0

# Cross-Timeframe Feature Engineering
feature_config:
  # Timeframe feature specifications
  timeframe_specs:
    "1h":
      fuzzy_features:
        - "rsi_membership"
        - "trend_membership"
        - "volume_membership"
        - "momentum_strength"
      indicator_features:
        - "rsi_14"
        - "sma_20"
        - "ema_12"
      weight: 1.0
      enabled: true
    
    "4h":
      fuzzy_features:
        - "rsi_membership"
        - "trend_membership"
        - "momentum_strength"
      indicator_features:
        - "rsi_14"
        - "sma_50"
        - "ema_21"
      weight: 0.8
      enabled: true
    
    "1d":
      fuzzy_features:
        - "rsi_membership"
        - "trend_membership"
      indicator_features:
        - "rsi_14"
        - "sma_200"
      weight: 0.6
      enabled: true

  # Cross-timeframe feature engineering
  cross_timeframe_features:
    enabled_features:
      - "correlation"
      - "divergence"
      - "momentum_cascade"
      - "volatility_regime"
      - "trend_alignment"
      - "support_resistance"
      - "seasonality"
    
    normalize_features: true
    
    correlation:
      window: 20
      min_correlation: 0.1
    
    divergence:
      momentum_period: 10
      rsi_threshold: 10
    
    momentum_cascade:
      alignment_threshold: 0.7
      consistency_weight: 0.8
    
    volatility_regime:
      percentiles: [0.33, 0.67]
      lookback_period: 50
    
    trend_alignment:
      short_window: 10
      long_window: 20
      confirmation_threshold: 0.6

  # Feature scaling configuration
  scaling:
    enabled: true
    type: "robust"                   # Robust scaling for outliers
    clip_outliers: true
    outlier_threshold: 3.0

# Training Pipeline Configuration
training_config:
  # Label generation using ZigZag method
  labeling:
    method: "zigzag"
    min_change_percent: 0.025        # 2.5% minimum price change
    min_bars: 5                      # Minimum 5 bars for signal
    smoothing: true                  # Apply smoothing to reduce noise
  
  # Data splitting
  validation_split: 0.2              # 20% for validation
  test_split: 0.1                    # 10% for final testing
  random_seed: 42                    # For reproducibility
  
  # Model persistence
  model_saving:
    save_best_model: true
    save_checkpoints: true
    checkpoint_frequency: 20         # Save every 20 epochs
    model_directory: "models/multi_timeframe"
  
  # Training monitoring
  monitoring:
    log_frequency: 10                # Log every 10 epochs
    plot_training_curves: true
    save_training_history: true
    calculate_feature_importance: true

# Advanced Training Features
advanced_features:
  # Ensemble training
  ensemble:
    enabled: false                   # Disable for single model
    num_models: 5
    voting_strategy: "soft"
  
  # Transfer learning
  transfer_learning:
    enabled: false
    pretrained_model_path: null
    freeze_layers: []
  
  # Hyperparameter optimization
  hyperparameter_tuning:
    enabled: false
    method: "optuna"                 # or "grid_search", "random_search"
    n_trials: 100
    optimization_metric: "val_accuracy"

# Output Configuration
output:
  # Training reports
  generate_reports: true
  report_formats: ["json", "html"]
  
  # Model artifacts
  save_feature_scaler: true
  save_preprocessing_config: true
  save_training_metadata: true
  
  # Visualization
  create_visualizations: true
  plot_formats: ["png", "pdf"]