"""Docker Compose override file generation for kinfra.

Generates docker-compose.override.yml that mounts worktree code into slot containers.
"""

from datetime import datetime
from pathlib import Path

from ktrdr.cli.sandbox_registry import SlotInfo

OVERRIDE_TEMPLATE = """\
# Generated by: kinfra impl
# Claimed by: {worktree_path}
# Generated at: {timestamp}
# Do not edit manually - regenerated on each claim

services:
  backend:
    volumes:
      - {worktree_path}/ktrdr:/app/ktrdr
      - {worktree_path}/research_agents:/app/research_agents
      - {worktree_path}/tests:/app/tests
      - {worktree_path}/config:/app/config:ro
      - {main_repo_path}/data:/app/data
      - {main_repo_path}/models:/app/models
      - {main_repo_path}/strategies:/app/strategies

  backtest-worker:
    volumes:
      - {worktree_path}/ktrdr:/app/ktrdr
      - {worktree_path}/research_agents:/app/research_agents
      - {main_repo_path}/data:/app/data
      - {main_repo_path}/models:/app/models
      - {main_repo_path}/strategies:/app/strategies

  training-worker:
    volumes:
      - {worktree_path}/ktrdr:/app/ktrdr
      - {worktree_path}/research_agents:/app/research_agents
      - {main_repo_path}/data:/app/data
      - {main_repo_path}/models:/app/models
      - {main_repo_path}/strategies:/app/strategies
"""


def generate_override(
    slot: SlotInfo, worktree_path: Path, main_repo_path: Path | None = None
) -> None:
    """Generate docker-compose.override.yml for a claimed slot.

    Args:
        slot: The slot info with infrastructure_path
        worktree_path: Path to the worktree to mount
        main_repo_path: Path to main repo for shared data dirs (defaults to cwd)
    """
    if main_repo_path is None:
        main_repo_path = Path.cwd()

    content = OVERRIDE_TEMPLATE.format(
        worktree_path=worktree_path,
        main_repo_path=main_repo_path,
        timestamp=datetime.now().isoformat(),
    )

    override_path = slot.infrastructure_path / "docker-compose.override.yml"
    override_path.write_text(content)


def remove_override(slot: SlotInfo) -> None:
    """Remove docker-compose.override.yml.

    Args:
        slot: The slot info with infrastructure_path
    """
    override_path = slot.infrastructure_path / "docker-compose.override.yml"
    override_path.unlink(missing_ok=True)
