name: KTRDR Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'ktrdr/**/*.py'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install -r requirements-dev.txt
          uv pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-awesome-pages-plugin
      
      - name: Generate API documentation
        run: |
          source .venv/bin/activate
          # Check if the script exists
          if [ -f scripts/generate_api_docs.py ]; then
            python -m scripts.generate_api_docs
          else
            echo "API documentation generation script not found. Skipping this step."
          fi
      
      - name: Build documentation
        run: |
          source .venv/bin/activate
          # Check if mkdocs.yml exists
          if [ -f mkdocs.yml ]; then
            mkdocs build --verbose --site-dir public
          else
            # Create a basic documentation site if no mkdocs.yml exists
            mkdir -p public
            cp -r docs/* public/ || true
            cp README.md public/index.md || true
            echo "No mkdocs.yml found. Created a basic documentation site."
          fi
      
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation-site
          path: public/
          retention-days: 7

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-docs
    
    # Deploy documentation only from main branch or manual dispatch
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download documentation
        uses: actions/download-artifact@v3
        with:
          name: documentation-site
          path: public
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: update documentation site'